/* 
* jqGrid  3.6.3 - jQuery Grid 
* Copyright (c) 2008, Tony Tomov, tony@trirand.com 
* Dual licensed under the MIT and GPL licenses 
* http://www.opensource.org/licenses/mit-license.php 
* http://www.gnu.org/licenses/gpl.html 
* Date:2010-02-07 
* Modules: grid.base.js; jquery.fmatter.js; grid.custom.js; grid.import.js; JsonXml.js; 
*/
(function(b){b.jgrid=b.jgrid||{};b.extend(b.jgrid,{htmlDecode:function(f){if(f=="&nbsp;"||f=="&#160;"||f.length==1&&f.charCodeAt(0)==160)return"";return!f?f:String(f).replace(/&amp;/g,"&").replace(/&gt;/g,">").replace(/&lt;/g,"<").replace(/&quot;/g,'"')},htmlEncode:function(f){return!f?f:String(f).replace(/&/g,"&amp;").replace(/>/g,"&gt;").replace(/</g,"&lt;").replace(/\"/g,"&quot;")},format:function(f){var k=b.makeArray(arguments).slice(1);if(f===undefined)f="";return f.replace(/\{(\d+)\}/g,function(i,
h){return k[h]})},getCellIndex:function(f){f=b(f);f=(!f.is("td")&&!f.is("th")?f.closest("td,th"):f)[0];if(b.browser.msie)return b.inArray(f,f.parentNode.cells);return f.cellIndex},stripHtml:function(f){f+="";var k=/<("[^"]*"|'[^']*'|[^'">])*>/gi;if(f)return(f=f.replace(k,""))&&f!=="&nbsp;"&&f!=="&#160;"?f:"";else return f},stringToDoc:function(f){var k;if(typeof f!=="string")return f;try{k=(new DOMParser).parseFromString(f,"text/xml")}catch(i){k=new ActiveXObject("Microsoft.XMLDOM");k.async=false;
k.loadXML(f)}return k&&k.documentElement&&k.documentElement.tagName!="parsererror"?k:null},parse:function(f){f=f;if(f.substr(0,9)=="while(1);")f=f.substr(9);if(f.substr(0,2)=="/*")f=f.substr(2,f.length-4);f||(f="{}");f=b.jgrid.useJSON===true&&typeof JSON==="object"&&typeof JSON.parse==="function"?JSON.parse(f):eval("("+f+")");return f.hasOwnProperty("d")?f.d:f},empty:function(){for(;this.firstChild;)this.removeChild(this.firstChild)},jqID:function(f){f+="";return f.replace(/([\.\:\[\]])/g,"\\$1")},
ajaxOptions:{},extend:function(f){b.extend(b.fn.jqGrid,f);this.no_legacy_api||b.fn.extend(f)}});b.fn.jqGrid=function(f){if(typeof f=="string"){var k=b.fn.jqGrid[f];if(!k)throw"jqGrid - No such method: "+f;var i=b.makeArray(arguments).slice(1);return k.apply(this,i)}return this.each(function(){if(!this.grid){var h=b.extend(true,{url:"",height:150,page:1,rowNum:20,records:0,pager:"",pgbuttons:true,pginput:true,colModel:[],rowList:[],colNames:[],sortorder:"asc",sortname:"",datatype:"xml",mtype:"GET",
altRows:false,selarrrow:[],savedRow:[],shrinkToFit:true,xmlReader:{},jsonReader:{},subGrid:false,subGridModel:[],reccount:0,lastpage:0,lastsort:0,selrow:null,beforeSelectRow:null,onSelectRow:null,onSortCol:null,ondblClickRow:null,onRightClickRow:null,onPaging:null,onSelectAll:null,loadComplete:null,gridComplete:null,loadError:null,loadBeforeSend:null,afterInsertRow:null,beforeRequest:null,onHeaderClick:null,viewrecords:false,loadonce:false,multiselect:false,multikey:false,editurl:null,search:false,
caption:"",hidegrid:true,hiddengrid:false,postData:{},userData:{},treeGrid:false,treeGridModel:"nested",treeReader:{},treeANode:-1,ExpandColumn:null,tree_root_level:0,prmNames:{page:"page",rows:"rows",sort:"sidx",order:"sord",search:"_search",nd:"nd",id:"id",oper:"oper",editoper:"edit",addoper:"add",deloper:"del"},forceFit:false,gridstate:"visible",cellEdit:false,cellsubmit:"remote",nv:0,loadui:"enable",toolbar:[false,""],scroll:false,multiboxonly:false,deselectAfterSort:true,scrollrows:false,autowidth:false,
scrollOffset:18,cellLayout:5,subGridWidth:20,multiselectWidth:20,gridview:false,rownumWidth:25,rownumbers:false,pagerpos:"center",recordpos:"right",footerrow:false,userDataOnFooter:false,hoverrows:true,altclass:"ui-priority-secondary",viewsortcols:[false,"vertical",true],resizeclass:"",autoencode:false,remapColumns:[],ajaxGridOptions:{},direction:"ltr",toppager:false},b.jgrid.defaults,f||{}),g={headers:[],cols:[],footers:[],dragStart:function(c,d,e){this.resizing={idx:c,startX:d.clientX,sOL:e[0]};
this.hDiv.style.cursor="col-resize";this.curGbox=b("#rs_m"+h.id,"#gbox_"+h.id);this.curGbox.css({display:"block",left:e[0],top:e[1],height:e[2]});b.isFunction(h.resizeStart)&&h.resizeStart.call(this,d,c);document.onselectstart=new Function("return false")},dragMove:function(c){if(this.resizing){var d=c.clientX-this.resizing.startX;c=this.headers[this.resizing.idx];var e=h.direction==="ltr"?c.width+d:c.width-d,l;if(e>33){this.curGbox.css({left:this.resizing.sOL+d});if(h.forceFit===true){l=this.headers[this.resizing.idx+
h.nv];d=h.direction==="ltr"?l.width-d:l.width+d;if(d>33){c.newWidth=e;l.newWidth=d}}else{this.newWidth=h.direction==="ltr"?h.tblwidth+d:h.tblwidth-d;c.newWidth=e}}}},dragEnd:function(){this.hDiv.style.cursor="default";if(this.resizing){var c=this.resizing.idx,d=this.headers[c].newWidth||this.headers[c].width;d=parseInt(d,10);this.resizing=false;b("#rs_m"+h.id).css("display","none");h.colModel[c].width=d;this.headers[c].width=d;this.headers[c].el.style.width=d+"px";if(this.cols.length>0)this.cols[c].style.width=
d+"px";if(this.footers.length>0)this.footers[c].style.width=d+"px";if(h.forceFit===true){d=this.headers[c+h.nv].newWidth||this.headers[c+h.nv].width;this.headers[c+h.nv].width=d;this.headers[c+h.nv].el.style.width=d+"px";if(this.cols.length>0)this.cols[c+h.nv].style.width=d+"px";if(this.footers.length>0)this.footers[c+h.nv].style.width=d+"px";h.colModel[c+h.nv].width=d}else{h.tblwidth=this.newWidth||h.tblwidth;b("table:first",this.bDiv).css("width",h.tblwidth+"px");b("table:first",this.hDiv).css("width",
h.tblwidth+"px");this.hDiv.scrollLeft=this.bDiv.scrollLeft;if(h.footerrow){b("table:first",this.sDiv).css("width",h.tblwidth+"px");this.sDiv.scrollLeft=this.bDiv.scrollLeft}}b.isFunction(h.resizeStop)&&h.resizeStop.call(this,d,c)}this.curGbox=null;document.onselectstart=new Function("return true")},populateVisible:function(){g.timer&&clearTimeout(g.timer);g.timer=null;var c=b(g.bDiv).height();if(c){var d=b("table:first",g.bDiv),e=b("> tbody > tr:visible:first",d).outerHeight()||g.prevRowHeight;if(e){g.prevRowHeight=
e;var l=h.rowNum,n=g.scrollTop=g.bDiv.scrollTop,s=Math.round(d.position().top)-n,p=s+d.height();e=e*l;var w,r,o;if(s<=0&&p<c&&(h.lastpage==null||parseInt((p+n+e-1)/e,10)<h.lastpage)){r=parseInt((c-p+e-1)/e,10);if(p>=0||r<2||h.scroll===true){w=Math.round((p+n)/e)+1;s=-1}else s=1}if(s>0){w=parseInt(n/e,10)+1;r=parseInt((n+c)/e,10)+2-w;o=true}if(r)if(!(h.lastpage&&w>h.lastpage))if(g.hDiv.loading)g.timer=setTimeout(g.populateVisible,200);else{h.page=w;if(o){g.selectionPreserver(d[0]);g.emptyRows(g.bDiv)}g.populate(r)}}}},
scrollGrid:function(){if(h.scroll){var c=g.bDiv.scrollTop;if(c!=g.scrollTop){g.scrollTop=c;g.timer&&clearTimeout(g.timer);g.timer=setTimeout(g.populateVisible,200)}}g.hDiv.scrollLeft=g.bDiv.scrollLeft;if(h.footerrow)g.sDiv.scrollLeft=g.bDiv.scrollLeft},selectionPreserver:function(c){var d=c.p,e=d.selrow,l=d.selarrrow?b.makeArray(d.selarrrow):null,n=c.grid.bDiv.scrollLeft,s=d.gridComplete;d.gridComplete=function(){d.selrow=null;d.selarrrow=[];if(d.multiselect&&l&&l.length>0)for(var p=0;p<l.length;p++)l[p]!=
e&&b(c).jqGrid("setSelection",l[p],false);e&&b(c).jqGrid("setSelection",e,false);c.grid.bDiv.scrollLeft=n;if(d.gridComplete=s)s()}}};this.p=h;var j,m,a;if(this.p.colNames.length===0)for(j=0;j<this.p.colModel.length;j++)this.p.colNames[j]=this.p.colModel[j].label||this.p.colModel[j].name;if(this.p.colNames.length!==this.p.colModel.length)alert(b.jgrid.errors.model);else{var q=b("<div class='ui-jqgrid-view'></div>"),u,y=b.browser.msie?true:false,B=b.browser.safari?true:false;a=this;a.p.direction=b.trim(a.p.direction.toLowerCase());
if(b.inArray(a.p.direction,["ltr","rtl"])==-1)a.p.direction="ltr";m=a.p.direction;b(q).insertBefore(this);b(this).appendTo(q).removeClass("scroll");var K=b("<div class='ui-jqgrid ui-widget ui-widget-content ui-corner-all'></div>");b(K).insertBefore(q).attr({id:"gbox_"+this.id,dir:m});b(q).appendTo(K).attr("id","gview_"+this.id);u=y&&b.browser.version<=6?'<iframe style="display:block;position:absolute;z-index:-1;filter:Alpha(Opacity=\'0\');" src="javascript:false;"></iframe>':"";b("<div class='ui-widget-overlay jqgrid-overlay' id='lui_"+
this.id+"'></div>").append(u).insertBefore(q);b("<div class='loading ui-state-default ui-state-active' id='load_"+this.id+"'>"+this.p.loadtext+"</div>").insertBefore(q);b(this).attr({cellSpacing:"0",cellPadding:"0",border:"0",role:"grid","aria-multiselectable":!!this.p.multiselect,"aria-labelledby":"gbox_"+this.id});var J=function(c,d){c=parseInt(c,10);return isNaN(c)?d?d:0:c},F=function(c,d){var e=a.p.colModel[c].align,l='style="',n=a.p.colModel[c].classes;if(e)l+="text-align:"+e+";";if(a.p.colModel[c].hidden===
true)l+="display:none;";if(d===0)l+="width: "+g.headers[c].width+"px;";return l+'"'+(n!==undefined?' class="'+n+'"':"")},S=function(c,d,e,l,n){c=M(c,d,e,n,"add");return'<td role="gridcell" '+F(e,l)+' title="'+b.jgrid.stripHtml(c)+'">'+c+"</td>"},M=function(c,d,e,l,n){e=a.p.colModel[e];if(typeof e.formatter!=="undefined"){c={rowId:c,colModel:e,gid:a.p.id};d=b.isFunction(e.formatter)?e.formatter.call(a,d,c,l,n):b.fmatter?b.fn.fmatter(e.formatter,d,c,l,n):t(d)}else d=t(d);return d},t=function(c){return c===
undefined||c===null||c===""?"&#160;":a.p.autoencode?b.jgrid.htmlEncode(c):c+""},ia=function(c,d,e){c='<input type="checkbox" id="jqg_'+c+'" class="cbox" name="jqg_'+c+'"/>';return"<td role='gridcell' "+F(d,e)+">"+c+"</td>"},aa=function(c,d,e,l){e=(parseInt(e,10)-1)*parseInt(l,10)+1+d;return'<td role="gridcell" class="ui-state-default jqgrid-rownum" '+F(c,d)+">"+e+"</td>"},ja=function(c){var d,e=[],l=0,n;for(n=0;n<a.p.colModel.length;n++){d=a.p.colModel[n];if(d.name!=="cb"&&d.name!=="subgrid"&&d.name!==
"rn"){e[l]=c=="xml"?d.xmlmap||d.name:d.jsonmap||d.name;l++}}return e},pa=function(c){var d=a.p.remapColumns;if(!d||!d.length)d=b.map(a.p.colModel,function(e,l){return l});if(c)d=b.map(d,function(e){return e<c?null:e-c});return d},$=function(c,d){var e=b("tbody:first",c);if(!a.p.gridview||a.p.jqgdnd)b("*",e).children().unbind();if(y)b.jgrid.empty.apply(e[0]);else e[0].innerHTML="";if(d&&a.p.scroll){b(">div:first",c).css({height:"auto"}).children("div:first").css({height:0,display:"none"});c.scrollTop=
0}},T=function(c,d){var e,l;e=c[d];if(e===undefined){if(typeof d==="string")l=d.split(".");if(l.length)for(e=c;e&&l.length;){c=l.shift();e=e[c]}}return e},qa=function(c,d,e,l,n){var s=new Date;a.p.reccount=0;if(b.isXMLDoc(c)){if(a.p.treeANode===-1&&!a.p.scroll){$(d);e=0}else e=e>0?e:0;var p,w=0,r,o,v=0,x=0,z=0,D,N,L=[],P,G={},ba=a.rows.length,E,V,C=[],Q=0,da=a.p.altRows===true?" "+a.p.altclass:"";a.p.xmlReader.repeatitems||(L=ja("xml"));D=a.p.keyIndex===false?a.p.xmlReader.id:a.p.keyIndex;if(L.length>
0&&!isNaN(D)){if(a.p.remapColumns&&a.p.remapColumns.length)D=b.inArray(D,a.p.remapColumns);D=L[D]}N=(D+"").indexOf("[")===-1?L.length?function(W,U){return b(D,W).text()||U}:function(W,U){return b(a.p.xmlReader.cell,W).eq(D).text()||U}:function(W,U){return W.getAttribute(D.replace(/[\[\]]/g,""))||U};b(a.p.xmlReader.page,c).each(function(){a.p.page=this.textContent||this.text||1});b(a.p.xmlReader.total,c).each(function(){a.p.lastpage=this.textContent||this.text;if(a.p.lastpage===undefined)a.p.lastpage=
1});b(a.p.xmlReader.records,c).each(function(){a.p.records=this.textContent||this.text||0});b(a.p.xmlReader.userdata,c).each(function(){a.p.userData[this.getAttribute("name")]=this.textContent||this.text});c=b(a.p.xmlReader.root+" "+a.p.xmlReader.row,c);var ea=c.length,O=0;if(c&&ea){var ka=parseInt(a.p.rowNum,10),wa=a.p.scroll?(parseInt(a.p.page,10)-1)*ka+1:1;if(n)ka*=n+1;for(n=b.isFunction(a.p.afterInsertRow);O<ea;){E=c[O];V=N(E,wa+O);p=e==0?0:e+1;p=(p+O)%2==1?da:"";C[Q++]='<tr id="'+V+'" role="row" class ="ui-widget-content jqgrow ui-row-'+
a.p.direction+""+p+'">';if(a.p.rownumbers===true){C[Q++]=aa(0,O,a.p.page,a.p.rowNum);z=1}if(a.p.multiselect===true){C[Q++]=ia(V,z,O);v=1}if(a.p.subGrid===true){C[Q++]=b(a).jqGrid("addSubGridCell",v+z,O+e);x=1}if(a.p.xmlReader.repeatitems){P||(P=pa(v+x+z));var Aa=b(a.p.xmlReader.cell,E);b.each(P,function(W){var U=Aa[this];if(!U)return false;r=U.textContent||U.text;G[a.p.colModel[W+v+x+z].name]=r;C[Q++]=S(V,r,W+v+x+z,O+e,E)})}else for(p=0;p<L.length;p++){r=b(L[p],E).text();G[a.p.colModel[p+v+x+z].name]=
r;C[Q++]=S(V,r,p+v+x+z,O+e,E)}C[Q++]="</tr>";if(a.p.gridview===false){if(a.p.treeGrid===true){p=a.p.treeANode>=-1?a.p.treeANode:0;o=b(C.join(""))[0];try{b(a).jqGrid("setTreeNode",G,o)}catch(Ga){}ba===0?b("tbody:first",d).append(o):b(a.rows[O+p+e]).after(o)}else b("tbody:first",d).append(C.join(""));if(a.p.subGrid===true)try{b(a).jqGrid("addSubGrid",a.rows[a.rows.length-1],v+z)}catch(Ha){}n&&a.p.afterInsertRow.call(a,V,G,E);C=[];Q=0}G={};w++;O++;if(w==ka)break}}a.p.gridview===true&&b("tbody:first",
d).append(C.join(""));a.p.totaltime=new Date-s;if(w>0){a.grid.cols=a.rows[0].cells;if(a.p.records===0)a.p.records=ea}C=null;if(!a.p.treeGrid&&!a.p.scroll)a.grid.bDiv.scrollTop=0;a.p.reccount=w;a.p.treeANode=-1;a.p.userDataOnFooter&&b(a).jqGrid("footerData","set",a.p.userData,true);l||la(false,true)}},ra=function(c,d,e,l,n){var s=new Date;a.p.reccount=0;if(c){if(a.p.treeANode===-1&&!a.p.scroll){$(d);e=0}else e=e>0?e:0;var p=0,w,r,o,v=[],x,z=0,D=0,N=0,L,P,G,ba={},E,V=a.rows.length,C;o=[];E=0;var Q=
a.p.altRows===true?" "+a.p.altclass:"";a.p.page=T(c,a.p.jsonReader.page)||1;G=T(c,a.p.jsonReader.total);a.p.lastpage=G===undefined?1:G;a.p.records=T(c,a.p.jsonReader.records)||0;a.p.userData=T(c,a.p.jsonReader.userdata)||{};a.p.jsonReader.repeatitems||(x=v=ja("json"));G=a.p.keyIndex===false?a.p.jsonReader.id:a.p.keyIndex;if(v.length>0&&!isNaN(G)){if(a.p.remapColumns&&a.p.remapColumns.length)G=b.inArray(G,a.p.remapColumns);G=v[G]}if(P=T(c,a.p.jsonReader.root)){L=P.length;c=0;var da=parseInt(a.p.rowNum,
10),ea=a.p.scroll?(parseInt(a.p.page,10)-1)*da+1:1;if(n)da*=n+1;for(var O=b.isFunction(a.p.afterInsertRow);c<L;){n=P[c];C=n[G];if(C===undefined){C=ea+c;if(v.length===0)if(a.p.jsonReader.cell)C=n[a.p.jsonReader.cell][G]||C}w=e==0?0:e+1;w=(w+c)%2==1?Q:"";o[E++]='<tr id="'+C+'" role="row" class= "ui-widget-content jqgrow ui-row-'+a.p.direction+""+w+'">';if(a.p.rownumbers===true){o[E++]=aa(0,c,a.p.page,a.p.rowNum);N=1}if(a.p.multiselect){o[E++]=ia(C,N,c);z=1}if(a.p.subGrid){o[E++]=b(a).jqGrid("addSubGridCell",
z+N,c+e);D=1}if(a.p.jsonReader.repeatitems){if(a.p.jsonReader.cell)n=T(n,a.p.jsonReader.cell);x||(x=pa(z+D+N))}for(r=0;r<x.length;r++){w=T(n,x[r]);o[E++]=S(C,w,r+z+D+N,c+e,n);ba[a.p.colModel[r+z+D+N].name]=w}o[E++]="</tr>";if(a.p.gridview===false){if(a.p.treeGrid===true){E=a.p.treeANode>=-1?a.p.treeANode:0;o=b(o.join(""))[0];try{b(a).jqGrid("setTreeNode",ba,o)}catch(ka){}V===0?b("tbody:first",d).append(o):b(a.rows[c+E+e]).after(o)}else b("tbody:first",d).append(o.join(""));if(a.p.subGrid===true)try{b(a).jqGrid("addSubGrid",
a.rows[a.rows.length-1],z+N)}catch(wa){}O&&a.p.afterInsertRow.call(a,C,ba,n);o=[];E=0}ba={};p++;c++;if(p==da)break}a.p.gridview===true&&b("tbody:first",d).append(o.join(""));a.p.totaltime=new Date-s;if(p>0){a.grid.cols=a.rows[0].cells;if(a.p.records===0)a.p.records=L}}if(!a.p.treeGrid&&!a.p.scroll)a.grid.bDiv.scrollTop=0;a.p.reccount=p;a.p.treeANode=-1;a.p.userDataOnFooter&&b(a).jqGrid("footerData","set",a.p.userData,true);l||la(false,true)}},la=function(c,d){var e,l,n,s,p,w,r,o="";n=(parseInt(a.p.page,
10)-1)*parseInt(a.p.rowNum,10);p=n+a.p.reccount;if(a.p.scroll){e=b("tbody:first > tr",a.grid.bDiv);n=p-e.length;if(l=e.outerHeight()){e=n*l;l=parseInt(a.p.records,10)*l;b(">div:first",a.grid.bDiv).css({height:l}).children("div:first").css({height:e,display:e?"":"none"})}}o=a.p.pager?a.p.pager:"";o+=a.p.toppager?o?","+a.p.toppager:a.p.toppager:"";if(o){r=b.jgrid.formatter.integer||{};if(a.p.loadonce){e=l=1;a.p.lastpage=a.page=1;b(".selbox",o).attr("disabled",true)}else{e=J(a.p.page,1);l=J(a.p.lastpage,
1);b(".selbox",o).attr("disabled",false)}if(a.p.pginput===true){b(".ui-pg-input",o).val(a.p.page);b("#sp_1",o).html(b.fmatter?b.fmatter.util.NumberFormat(a.p.lastpage,r):a.p.lastpage)}if(a.p.viewrecords)if(a.p.reccount===0)b(".ui-paging-info",o).html(a.p.emptyrecords);else{s=n+1;w=a.p.records;if(b.fmatter){s=b.fmatter.util.NumberFormat(s,r);p=b.fmatter.util.NumberFormat(p,r);w=b.fmatter.util.NumberFormat(w,r)}b(".ui-paging-info",o).html(b.jgrid.format(a.p.recordtext,s,p,w))}if(a.p.pgbuttons===true){if(e<=
0)e=l=1;if(e==1){b("#first, #prev",a.p.pager).addClass("ui-state-disabled").removeClass("ui-state-hover");a.p.toppager&&b("#first_t, #prev_t",a.p.toppager).addClass("ui-state-disabled").removeClass("ui-state-hover")}else{b("#first, #prev",a.p.pager).removeClass("ui-state-disabled");a.p.toppager&&b("#first_t, #prev_t",a.p.toppager).removeClass("ui-state-disabled")}if(e==l){b("#next, #last",a.p.pager).addClass("ui-state-disabled").removeClass("ui-state-hover");a.p.toppager&&b("#next_t, #last_t",a.p.toppager).addClass("ui-state-disabled").removeClass("ui-state-hover")}else{b("#next, #last",
a.p.pager).removeClass("ui-state-disabled");a.p.toppager&&b("#next_t, #last_t",a.p.toppager).removeClass("ui-state-disabled")}}}c===true&&a.p.rownumbers===true&&b("td.jqgrid-rownum",a.rows).each(function(v){b(this).html(n+1+v)});d&&a.p.jqgdnd&&b(a).jqGrid("gridDnD","updateDnD");b.isFunction(a.p.gridComplete)&&a.p.gridComplete.call(a)},X=function(c){if(!a.grid.hDiv.loading){var d=a.p.scroll&&c==false,e={},l,n=a.p.prmNames;if(n.search!==null)e[n.search]=a.p.search;if(n.nd!=null)e[n.nd]=(new Date).getTime();
if(n.rows!==null)e[n.rows]=a.p.rowNum;if(n.page!==null)e[n.page]=a.p.page;if(n.sort!==null)e[n.sort]=a.p.sortname;if(n.order!==null)e[n.order]=a.p.sortorder;var s=a.p.loadComplete,p=b.isFunction(s);p||(s=null);var w=0;c=c||1;if(c>1)if(n.npage!=null){e[n.npage]=c;w=c-1;c=1}else s=function(o){p&&a.p.loadComplete.call(a,o);a.grid.hDiv.loading=false;a.p.page++;X(c-1)};else n.npage!=null&&delete a.p.postData[n.npage];b.extend(a.p.postData,e);var r=!a.p.scroll?0:a.rows.length-1;if(b.isFunction(a.p.datatype))a.p.datatype.call(a,
a.p.postData,"load_"+a.p.id);else{b.isFunction(a.p.beforeRequest)&&a.p.beforeRequest.call(a);l=a.p.datatype.toLowerCase();switch(l){case "json":case "jsonp":case "xml":case "script":b.ajax(b.extend({url:a.p.url,type:a.p.mtype,dataType:l,data:b.isFunction(a.p.serializeGridData)?a.p.serializeGridData.call(a,a.p.postData):a.p.postData,complete:function(o,v){if(v=="success"||o.statusText=="OK"&&o.status=="200"){l==="xml"?qa(o.responseXML,a.grid.bDiv,r,c>1,w):ra(b.jgrid.parse(o.responseText),a.grid.bDiv,
r,c>1,w);s&&s.call(a,o);d&&a.grid.populateVisible()}fa()},error:function(o,v,x){b.isFunction(a.p.loadError)&&a.p.loadError.call(a,o,v,x);fa()},beforeSend:function(o){ma();b.isFunction(a.p.loadBeforeSend)&&a.p.loadBeforeSend.call(a,o)}},b.jgrid.ajaxOptions,a.p.ajaxGridOptions));if(a.p.loadonce||a.p.treeGrid)a.p.datatype="local";break;case "xmlstring":ma();e=b.jgrid.stringToDoc(a.p.datastr);p&&a.p.loadComplete.call(a,e);qa(e,a.grid.bDiv);a.p.datatype="local";a.p.datastr=null;fa();break;case "jsonstring":ma();
e=typeof a.p.datastr=="string"?b.jgrid.parse(a.p.datastr):a.p.datastr;p&&a.p.loadComplete.call(a,e);ra(e,a.grid.bDiv);a.p.datatype="local";a.p.datastr=null;fa();break;case "local":case "clientside":ma();a.p.datatype="local";p&&a.p.loadComplete.call(a,"");Ba();la(true,true);fa();break}}}},ma=function(){a.grid.hDiv.loading=true;if(!a.p.hiddengrid)switch(a.p.loadui){case "disable":break;case "enable":b("#load_"+a.p.id).show();break;case "block":b("#lui_"+a.p.id).show();b("#load_"+a.p.id).show();break}},
fa=function(){a.grid.hDiv.loading=false;switch(a.p.loadui){case "disable":break;case "enable":b("#load_"+a.p.id).hide();break;case "block":b("#lui_"+a.p.id).hide();b("#load_"+a.p.id).hide();break}},Ba=function(){var c=/[\$,%]/g,d=[],e=0,l,n,s,p=a.p.sortorder=="asc"?1:-1;b.each(a.p.colModel,function(r){if(this.index==a.p.sortname||this.name==a.p.sortname){e=a.p.lastsort=r;l=this.sorttype;return false}});s=l=="float"||l=="number"||l=="currency"?function(r){r=parseFloat(r.replace(c,""));return isNaN(r)?
0:r}:l=="int"||l=="integer"?function(r){return J(r.replace(c,""),0)}:l=="date"||l=="datetime"?function(r){return Ca(a.p.colModel[e].datefmt||"Y-m-d",r).getTime()}:function(r){return b.trim(r.toUpperCase())};b.each(a.rows,function(r,o){try{n=b.unformat(b(o).children("td").eq(e),{rowId:o.id,colModel:a.p.colModel[e]},e,true)}catch(v){n=b(o).children("td").eq(e).text()}o.sortKey=s(n);d[r]=this});if(a.p.treeGrid)b(a).jqGrid("SortTree",p);else{d.sort(function(r,o){if(r.sortKey<o.sortKey)return-p;if(r.sortKey>
o.sortKey)return p;return 0});if(d[0]){b("td",d[0]).each(function(r){b(this).css("width",g.headers[r].width+"px")});a.grid.cols=d[0].cells}var w="";if(a.p.altRows)w=a.p.altclass;b.each(d,function(r,o){if(w)r%2==1?b(o).addClass(w):b(o).removeClass(w);b("tbody",a.grid.bDiv).append(o);o.sortKey=null})}a.grid.bDiv.scrollTop=0},Ca=function(c,d){var e={m:1,d:1,y:1970,h:0,i:0,s:0},l,n,s;d=d.split(/[\\\/:_;.\t\T\s-]/);c=c.split(/[\\\/:_;.\t\T\s-]/);var p=b.jgrid.formatter.date.monthNames;l=0;for(n=c.length;l<
n;l++){if(c[l]=="M"){s=b.inArray(d[l],p);if(s!==-1&&s<12)d[l]=s+1}if(c[l]=="F"){s=b.inArray(d[l],p);if(s!==-1&&s>11)d[l]=s+1-12}e[c[l].toLowerCase()]=parseInt(d[l],10)}e.m=parseInt(e.m,10)-1;c=e.y;if(c>=70&&c<=99)e.y=1900+e.y;else if(c>=0&&c<=69)e.y=2E3+e.y;return new Date(e.y,e.m,e.d,e.h,e.i,e.s,0)};u=function(c,d){var e="",l="<table cellspacing='0' cellpadding='0' border='0' style='table-layout:auto;' class='ui-pg-table'><tbody><tr>",n="",s,p,w,r,o=function(v){a.p.selrow=null;if(a.p.multiselect){a.p.selarrrow=
[];b("#cb_"+b.jgrid.jqID(a.p.id),a.grid.hDiv).attr("checked",false)}a.p.savedRow=[];if(b.isFunction(a.p.onPaging))if(a.p.onPaging.call(a,v)=="stop")return false;return true};c=c.substr(1);s="pg_"+c;p=c+"_left";w=c+"_center";r=c+"_right";b("#"+c).append("<div id='"+s+"' class='ui-pager-control' role='group'><table cellspacing='0' cellpadding='0' border='0' class='ui-pg-table' style='width:100%;table-layout:fixed;' role='row'><tbody><tr><td id='"+p+"' align='left'></td><td id='"+w+"' align='center' style='white-space:pre;'></td><td id='"+
r+"' align='right'></td></tr></tbody></table></div>").attr("dir","ltr");if(a.p.rowList.length>0){n="<td dir='"+m+"'>";n+="<select class='ui-pg-selbox' role='listbox'>";for(p=0;p<a.p.rowList.length;p++)n+="<option role='option' value='"+a.p.rowList[p]+"'"+(a.p.rowNum==a.p.rowList[p]?" selected":"")+">"+a.p.rowList[p]+"</option>";n+="</select></td>"}if(m=="rtl")l+=n;if(a.p.pginput===true)e="<td dir='"+m+"'>"+b.jgrid.format(a.p.pgtext||"","<input class='ui-pg-input' type='text' size='2' maxlength='7' value='0' role='textbox'/>",
"<span id='sp_1'></span>")+"</td>";if(a.p.pgbuttons===true){p=["first"+d,"prev"+d,"next"+d,"last"+d];m=="rtl"&&p.reverse();l+="<td id='"+p[0]+"' class='ui-pg-button ui-corner-all'><span class='ui-icon ui-icon-seek-first'></span></td>";l+="<td id='"+p[1]+"' class='ui-pg-button ui-corner-all'><span class='ui-icon ui-icon-seek-prev'></span></td>";l+=e!=""?"<td class='ui-pg-button ui-state-disabled' style='width:4px;'><span class='ui-separator'></span></td>"+e+"<td class='ui-pg-button ui-state-disabled' style='width:4px;'><span class='ui-separator'></span></td>":
"";l+="<td id='"+p[2]+"' class='ui-pg-button ui-corner-all'><span class='ui-icon ui-icon-seek-next'></span></td>";l+="<td id='"+p[3]+"' class='ui-pg-button ui-corner-all'><span class='ui-icon ui-icon-seek-end'></span></td>"}else if(e!="")l+=e;if(m=="ltr")l+=n;l+="</tr></tbody></table>";a.p.viewrecords===true&&b("td#"+c+"_"+a.p.recordpos,"#"+s).append("<div dir='"+m+"' style='text-align:"+a.p.recordpos+"' class='ui-paging-info'></div>");b("td#"+c+"_"+a.p.pagerpos,"#"+s).append(l);n=b(".ui-jqgrid").css("font-size")||
"11px";b("body").append("<div id='testpg' class='ui-jqgrid ui-widget ui-widget-content' style='font-size:"+n+";visibility:hidden;' ></div>");l=b(l).clone().appendTo("#testpg").width();b("#testpg").remove();if(l>0){if(e!="")l+=50;b("td#"+c+"_"+a.p.pagerpos,"#"+s).width(l)}a.p._nvtd=[];a.p._nvtd[0]=l?Math.floor((a.p.width-l)/2):Math.floor(a.p.width/3);a.p._nvtd[1]=0;l=null;b(".ui-pg-selbox","#"+s).bind("change",function(){a.p.page=Math.round(a.p.rowNum*(a.p.page-1)/this.value-0.5)+1;a.p.rowNum=this.value;
if(d)b(".ui-pg-selbox",a.p.pager).val(this.value);else a.p.toppager&&b(".ui-pg-selbox",a.p.toppager).val(this.value);if(!o("records"))return false;X();return false});if(a.p.pgbuttons===true){b(".ui-pg-button","#"+s).hover(function(){if(b(this).hasClass("ui-state-disabled"))this.style.cursor="default";else{b(this).addClass("ui-state-hover");this.style.cursor="pointer"}},function(){if(!b(this).hasClass("ui-state-disabled")){b(this).removeClass("ui-state-hover");this.style.cursor="default"}});b("#first"+
d+", #prev"+d+", #next"+d+", #last"+d,"#"+c).click(function(){var v=J(a.p.page,1),x=J(a.p.lastpage,1),z=false,D=true,N=true,L=true,P=true;if(x===0||x===1)P=L=N=D=false;else if(x>1&&v>=1)if(v===1)N=D=false;else{if(!(v>1&&v<x))if(v===x)P=L=false}else if(x>1&&v===0){P=L=false;v=x-1}if(this.id==="first"+d&&D){a.p.page=1;z=true}if(this.id==="prev"+d&&N){a.p.page=v-1;z=true}if(this.id==="next"+d&&L){a.p.page=v+1;z=true}if(this.id==="last"+d&&P){a.p.page=x;z=true}if(z){if(!o(this.id))return false;X()}return false})}a.p.pginput===
true&&b("input.ui-pg-input","#"+s).keypress(function(v){if((v.charCode?v.charCode:v.keyCode?v.keyCode:0)==13){a.p.page=b(this).val()>0?b(this).val():a.p.page;if(!o("user"))return false;X();return false}return this})};var xa=function(c,d,e,l){if(a.p.colModel[d].sortable)if(!(a.p.savedRow.length>0)){if(!e){if(a.p.lastsort==d)if(a.p.sortorder=="asc")a.p.sortorder="desc";else{if(a.p.sortorder=="desc")a.p.sortorder="asc"}else a.p.sortorder="asc";a.p.page=1}if(l)if(a.p.lastsort==d&&a.p.sortorder==l)return;
else a.p.sortorder=l;e=b("thead:first",a.grid.hDiv).get(0);b("tr th:eq("+a.p.lastsort+") span.ui-grid-ico-sort",e).addClass("ui-state-disabled");b("tr th:eq("+a.p.lastsort+")",e).attr("aria-selected","false");b("tr th:eq("+d+") span.ui-icon-"+a.p.sortorder,e).removeClass("ui-state-disabled");b("tr th:eq("+d+")",e).attr("aria-selected","true");if(!a.p.viewsortcols[0])if(a.p.lastsort!=d){b("tr th:eq("+a.p.lastsort+") span.s-ico",e).hide();b("tr th:eq("+d+") span.s-ico",e).show()}a.p.lastsort=d;c=c.substring(5);
a.p.sortname=a.p.colModel[d].index||c;e=a.p.sortorder;if(b.isFunction(a.p.onSortCol))if(a.p.onSortCol.call(a,c,d,e)=="stop")return;if(a.p.datatype=="local")a.p.deselectAfterSort&&b(a).jqGrid("resetSelection");else{a.p.selrow=null;a.p.multiselect&&b("#cb_"+b.jgrid.jqID(a.p.id),a.grid.hDiv).attr("checked",false);a.p.selarrrow=[];a.p.savedRow=[];a.p.scroll&&$(a.grid.bDiv,true)}a.p.subGrid&&a.p.datatype=="local"&&b("td.sgexpanded","#"+a.p.id).each(function(){b(this).trigger("click")});X();if(a.p.sortname!=
c&&d)a.p.lastsort=d}},Da=function(c){var d=c,e;for(e=c+1;e<a.p.colModel.length;e++)if(a.p.colModel[e].hidden!==true){d=e;break}return d-c},Ea=function(c){var d,e={},l=B?0:a.p.cellLayout;for(d=e[0]=e[1]=e[2]=0;d<=c;d++)if(a.p.colModel[d].hidden===false)e[0]+=a.p.colModel[d].width+l;if(a.p.direction=="rtl")e[0]=a.p.width-e[0];e[0]-=a.grid.bDiv.scrollLeft;if(b(a.grid.cDiv).is(":visible"))e[1]+=b(a.grid.cDiv).height()+parseInt(b(a.grid.cDiv).css("padding-top"),10)+parseInt(b(a.grid.cDiv).css("padding-bottom"),
10);if(a.p.toolbar[0]==true&&(a.p.toolbar[1]=="top"||a.p.toolbar[1]=="both"))e[1]+=b(a.grid.uDiv).height()+parseInt(b(a.grid.uDiv).css("border-top-width"),10)+parseInt(b(a.grid.uDiv).css("border-bottom-width"),10);if(a.p.toppager)e[1]+=b(a.grid.topDiv).height()+parseInt(b(a.grid.topDiv).css("border-bottom-width"),10);e[2]+=b(a.grid.bDiv).height()+b(a.grid.hDiv).height();return e};this.p.id=this.id;if(b.inArray(a.p.multikey,["shiftKey","altKey","ctrlKey"])==-1)a.p.multikey=false;a.p.keyIndex=false;
for(j=0;j<a.p.colModel.length;j++)if(a.p.colModel[j].key===true){a.p.keyIndex=j;break}a.p.sortorder=a.p.sortorder.toLowerCase();if(this.p.treeGrid===true)try{b(this).jqGrid("setTreeGrid")}catch(Ia){}if(this.p.subGrid)try{b(a).jqGrid("setSubGrid")}catch(Ja){}if(this.p.multiselect){this.p.colNames.unshift("<input id='cb_"+this.p.id+"' class='cbox' type='checkbox'/>");this.p.colModel.unshift({name:"cb",width:B?a.p.multiselectWidth+a.p.cellLayout:a.p.multiselectWidth,sortable:false,resizable:false,hidedlg:true,
search:false,align:"center",fixed:true})}if(this.p.rownumbers){this.p.colNames.unshift("");this.p.colModel.unshift({name:"rn",width:a.p.rownumWidth,sortable:false,resizable:false,hidedlg:true,search:false,align:"center",fixed:true})}a.p.xmlReader=b.extend(true,{root:"rows",row:"row",page:"rows>page",total:"rows>total",records:"rows>records",repeatitems:true,cell:"cell",id:"[id]",userdata:"userdata",subgrid:{root:"rows",row:"row",repeatitems:true,cell:"cell"}},a.p.xmlReader);a.p.jsonReader=b.extend(true,
{root:"rows",page:"page",total:"total",records:"records",repeatitems:true,cell:"cell",id:"id",userdata:"userdata",subgrid:{root:"rows",repeatitems:true,cell:"cell"}},a.p.jsonReader);if(a.p.scroll){a.p.pgbuttons=false;a.p.pginput=false;a.p.rowList=[]}var H="<thead><tr class='ui-jqgrid-labels' role='rowheader'>",ya,ga,sa,ha,na,I,A,ca;ga=ca="";if(a.p.shrinkToFit===true&&a.p.forceFit===true)for(j=a.p.colModel.length-1;j>=0;j--)if(!a.p.colModel[j].hidden){a.p.colModel[j].resizable=false;break}if(a.p.viewsortcols[1]==
"horizontal"){ca=" ui-i-asc";ga=" ui-i-desc"}ya=y?"class='ui-th-div-ie'":"";ca="<span class='s-ico' style='display:none'><span sort='asc' class='ui-grid-ico-sort ui-icon-asc"+ca+" ui-state-disabled ui-icon ui-icon-triangle-1-n ui-sort-"+m+"'></span>";ca+="<span sort='desc' class='ui-grid-ico-sort ui-icon-desc"+ga+" ui-state-disabled ui-icon ui-icon-triangle-1-s ui-sort-"+m+"'></span></span>";for(j=0;j<this.p.colNames.length;j++){H+="<th role='columnheader' class='ui-state-default ui-th-column ui-th-"+
m+"'>";ga=a.p.colModel[j].index||a.p.colModel[j].name;H+="<div id='jqgh_"+a.p.colModel[j].name+"' "+ya+">"+a.p.colNames[j];if(ga==a.p.sortname)a.p.lastsort=j;H+=ca+"</div></th>"}H+="</tr></thead>";b(this).append(H);b("thead tr:first th",this).hover(function(){b(this).addClass("ui-state-hover")},function(){b(this).removeClass("ui-state-hover")});if(this.p.multiselect){var za=true,ta=[],oa;if(typeof a.p.onSelectAll!=="function")za=false;b("#cb_"+b.jgrid.jqID(a.p.id),this).bind("click",function(){if(this.checked){b("[id^=jqg_]",
a.rows).attr("checked",true);b(a.rows).each(function(c){if(!b(this).hasClass("subgrid")){b(this).addClass("ui-state-highlight").attr("aria-selected","true");a.p.selarrrow[c]=a.p.selrow=this.id}});oa=true;ta=[]}else{b("[id^=jqg_]",a.rows).attr("checked",false);b(a.rows).each(function(c){if(!b(this).hasClass("subgrid")){b(this).removeClass("ui-state-highlight").attr("aria-selected","false");ta[c]=this.id}});a.p.selarrrow=[];a.p.selrow=null;oa=false}if(za)a.p.onSelectAll.call(a,oa?a.p.selarrrow:ta,oa)})}b.each(a.p.colModel,
function(){if(!this.width)this.width=150;this.width=parseInt(this.width,10)});if(a.p.autowidth===true){H=b(K).innerWidth();a.p.width=H>0?H:"nw"}(function(){var c=0,d=a.p.cellLayout,e=0,l,n=a.p.scrollOffset,s,p=false,w,r=0,o=0,v=0,x;if(B)d=0;b.each(a.p.colModel,function(){if(typeof this.hidden==="undefined")this.hidden=false;if(this.hidden===false){c+=J(this.width,0);if(this.fixed){r+=this.width;o+=this.width+d}else e++;v++}});if(isNaN(a.p.width))a.p.width=g.width=c;else g.width=a.p.width;a.p.tblwidth=
c;if(a.p.shrinkToFit===false&&a.p.forceFit===true)a.p.forceFit=false;if(a.p.shrinkToFit===true&&e>0){w=g.width-d*e-o;if(!isNaN(a.p.height)){w-=n;p=true}c=0;b.each(a.p.colModel,function(z){if(this.hidden===false&&!this.fixed){this.width=s=Math.floor(w/(a.p.tblwidth-r)*this.width);c+=s;l=z}});x=0;if(p){if(g.width-o-(c+d*e)!==n)x=g.width-o-(c+d*e)-n}else if(!p&&Math.abs(g.width-o-(c+d*e))!==1)x=g.width-o-(c+d*e);a.p.colModel[l].width+=x;a.p.tblwidth=c+x+r+v*d}})();b(K).css("width",g.width+"px").append("<div class='ui-jqgrid-resize-mark' id='rs_m"+
a.p.id+"'>&#160;</div>");b(q).css("width",g.width+"px");H=b("thead:first",a).get(0);var ua="<table role='grid' style='width:"+a.p.tblwidth+"px' class='ui-jqgrid-ftable' cellspacing='0' cellpadding='0' border='0'><tbody><tr role='row' class='ui-widget-content footrow footrow-"+m+"'>";q=b("tr:first",H);a.p.disableClick=false;b("th",q).each(function(c){b("div",this);sa=a.p.colModel[c].width;if(typeof a.p.colModel[c].resizable==="undefined")a.p.colModel[c].resizable=true;if(a.p.colModel[c].resizable){ha=
document.createElement("span");b(ha).html("&#160;").addClass("ui-jqgrid-resize ui-jqgrid-resize-"+m);!b.browser.opera&&b(ha).css("cursor","col-resize");b(this).addClass(a.p.resizeclass)}else ha="";b(this).css("width",sa+"px").prepend(ha);a.p.colModel[c].hidden&&b(this).css("display","none");g.headers[c]={width:sa,el:this};na=a.p.colModel[c].sortable;if(typeof na!=="boolean")na=a.p.colModel[c].sortable=true;var d=a.p.colModel[c].name;d=="cb"||d=="subgrid"||d=="rn"||a.p.viewsortcols[2]&&b("div",this).addClass("ui-jqgrid-sortable");
if(na)if(a.p.viewsortcols[0]){b("div span.s-ico",this).show();c==a.p.lastsort&&b("div span.ui-icon-"+a.p.sortorder,this).removeClass("ui-state-disabled")}else if(c==a.p.lastsort){b("div span.s-ico",this).show();b("div span.ui-icon-"+a.p.sortorder,this).removeClass("ui-state-disabled")}ua+="<td role='gridcell' "+F(c,0)+">&#160;</td>"}).mousedown(function(c){if(b(c.target).closest("th>span.ui-jqgrid-resize").length==1){var d=b.jgrid.getCellIndex(this);if(a.p.forceFit===true)a.p.nv=Da(d);g.dragStart(d,
c,Ea(d));return false}}).click(function(c){if(a.p.disableClick)return a.p.disableClick=false;var d="th>div.ui-jqgrid-sortable",e,l;a.p.viewsortcols[2]||(d="th>div>span>span.ui-grid-ico-sort");c=b(c.target).closest(d);if(c.length==1){d=b.jgrid.getCellIndex(this);if(!a.p.viewsortcols[2]){e=true;l=c.attr("sort")}xa(b("div",this)[0].id,d,e,l);return false}});if(a.p.sortable&&b.fn.sortable)try{b(a).jqGrid("sortableColumns",q)}catch(Ka){}ua+="</tr></tbody></table>";this.appendChild(document.createElement("tbody"));
b(this).addClass("ui-jqgrid-btable");q=b("<table class='ui-jqgrid-htable' style='width:"+a.p.tblwidth+"px' role='grid' aria-labelledby='gbox_"+this.id+"' cellspacing='0' cellpadding='0' border='0'></table>").append(H);var R=a.p.caption&&a.p.hiddengrid===true?true:false;H=b("<div class='ui-jqgrid-hbox"+(m=="rtl"?"-rtl":"")+"'></div>");g.hDiv=document.createElement("div");b(g.hDiv).css({width:g.width+"px"}).addClass("ui-state-default ui-jqgrid-hdiv").append(H);b(H).append(q);R&&b(g.hDiv).hide();if(a.p.pager){if(typeof a.p.pager==
"string"){if(a.p.pager.substr(0,1)!="#")a.p.pager="#"+a.p.pager}else a.p.pager="#"+b(a.p.pager).attr("id");b(a.p.pager).css({width:g.width+"px"}).appendTo(K).addClass("ui-state-default ui-jqgrid-pager ui-corner-bottom");R&&b(a.p.pager).hide();u(a.p.pager,"")}a.p.cellEdit===false&&a.p.hoverrows===true&&b(a).bind("mouseover",function(c){A=b(c.target).closest("tr.jqgrow");b(A).attr("class")!=="subgrid"&&b(A).addClass("ui-state-hover");return false}).bind("mouseout",function(c){A=b(c.target).closest("tr.jqgrow");
b(A).removeClass("ui-state-hover");return false});var Y,Z;b(a).before(g.hDiv).click(function(c){I=c.target;var d=b(I).hasClass("cbox");A=b(I,a.rows).closest("tr.jqgrow");if(b(A).length===0)return this;var e=true;if(b.isFunction(a.p.beforeSelectRow))e=a.p.beforeSelectRow.call(a,A[0].id,c);if(I.tagName=="A"||(I.tagName=="INPUT"||I.tagName=="TEXTAREA"||I.tagName=="OPTION"||I.tagName=="SELECT")&&!d)return true;if(e===true){if(a.p.cellEdit===true)if(a.p.multiselect&&d)b(a).jqGrid("setSelection",A[0].id,
true);else{Y=A[0].rowIndex;Z=b.jgrid.getCellIndex(I);try{b(a).jqGrid("editCell",Y,Z,true)}catch(l){}}else if(a.p.multikey)if(c[a.p.multikey])b(a).jqGrid("setSelection",A[0].id,true);else{if(a.p.multiselect&&d){d=b("[id^=jqg_]",A).attr("checked");b("[id^=jqg_]",A).attr("checked",!d)}}else{if(a.p.multiselect&&a.p.multiboxonly)if(!d){b(a.p.selarrrow).each(function(n,s){n=a.rows.namedItem(s);b(n).removeClass("ui-state-highlight");b("#jqg_"+b.jgrid.jqID(s),n).attr("checked",false)});a.p.selarrrow=[];b("#cb_"+
b.jgrid.jqID(a.p.id),a.grid.hDiv).attr("checked",false)}b(a).jqGrid("setSelection",A[0].id,true)}if(b.isFunction(a.p.onCellSelect)){Y=A[0].id;Z=b.jgrid.getCellIndex(I);a.p.onCellSelect.call(a,Y,Z,b(I).html(),c)}}c.stopPropagation()}).bind("reloadGrid",function(c,d){if(a.p.treeGrid===true)a.p.datatype=a.p.treedatatype;d&&d.current&&a.grid.selectionPreserver(a);if(a.p.datatype=="local")b(a).jqGrid("resetSelection");else if(!a.p.treeGrid){a.p.selrow=null;if(a.p.multiselect){a.p.selarrrow=[];b("#cb_"+
b.jgrid.jqID(a.p.id),a.grid.hDiv).attr("checked",false)}a.p.savedRow=[];a.p.scroll&&$(a.grid.bDiv)}if(d&&d.page){c=d.page;if(c>a.p.lastpage)c=a.p.lastpage;if(c<1)c=1;a.p.page=c;a.grid.bDiv.scrollTop=a.grid.prevRowHeight?(c-1)*a.grid.prevRowHeight*a.p.rowNum:0}if(a.grid.prevRowHeight&&a.p.scroll){delete a.p.lastpage;a.grid.populateVisible()}else a.grid.populate();return false});b.isFunction(this.p.ondblClickRow)&&b(this).dblclick(function(c){I=c.target;A=b(I,a.rows).closest("tr.jqgrow");if(b(A).length===
0)return false;Y=A[0].rowIndex;Z=b.jgrid.getCellIndex(I);a.p.ondblClickRow.call(a,b(A).attr("id"),Y,Z,c);return false});b.isFunction(this.p.onRightClickRow)&&b(this).bind("contextmenu",function(c){I=c.target;A=b(I,a.rows).closest("tr.jqgrow");if(b(A).length===0)return false;a.p.multiselect||b(a).jqGrid("setSelection",A[0].id,true);Y=A[0].rowIndex;Z=b.jgrid.getCellIndex(I);a.p.onRightClickRow.call(a,b(A).attr("id"),Y,Z,c);return false});g.bDiv=document.createElement("div");b(g.bDiv).append(b('<div style="position:relative;'+
(y&&b.browser.version<8?"height:0.01%;":"")+'"></div>').append("<div></div>").append(this)).addClass("ui-jqgrid-bdiv").css({height:a.p.height+(isNaN(a.p.height)?"":"px"),width:g.width+"px"}).scroll(g.scrollGrid);b("table:first",g.bDiv).css({width:a.p.tblwidth+"px"});if(y){b("tbody",this).size()==2&&b("tbody:first",this).remove();a.p.multikey&&b(g.bDiv).bind("selectstart",function(){return false})}else a.p.multikey&&b(g.bDiv).bind("mousedown",function(){return false});R&&b(g.bDiv).hide();g.cDiv=document.createElement("div");
var va=a.p.hidegrid===true?b("<a role='link' href='javascript:void(0)'/>").addClass("ui-jqgrid-titlebar-close HeaderButton").hover(function(){va.addClass("ui-state-hover")},function(){va.removeClass("ui-state-hover")}).append("<span class='ui-icon ui-icon-circle-triangle-n'></span>").css(m=="rtl"?"left":"right","0px"):"";b(g.cDiv).append(va).append("<span class='ui-jqgrid-title"+(m=="rtl"?"-rtl":"")+"'>"+a.p.caption+"</span>").addClass("ui-jqgrid-titlebar ui-widget-header ui-corner-top ui-helper-clearfix");
b(g.cDiv).insertBefore(g.hDiv);if(a.p.toolbar[0]){g.uDiv=document.createElement("div");if(a.p.toolbar[1]=="top")b(g.uDiv).insertBefore(g.hDiv);else a.p.toolbar[1]=="bottom"&&b(g.uDiv).insertAfter(g.hDiv);if(a.p.toolbar[1]=="both"){g.ubDiv=document.createElement("div");b(g.uDiv).insertBefore(g.hDiv).addClass("ui-userdata ui-state-default").attr("id","t_"+this.id);b(g.ubDiv).insertAfter(g.hDiv).addClass("ui-userdata ui-state-default").attr("id","tb_"+this.id);R&&b(g.ubDiv).hide()}else b(g.uDiv).width(g.width).addClass("ui-userdata ui-state-default").attr("id",
"t_"+this.id);R&&b(g.uDiv).hide()}if(a.p.toppager){a.p.toppager=a.p.id+"_toppager";g.topDiv=b("<div id='"+a.p.toppager+"'></div>")[0];a.p.toppager="#"+a.p.toppager;b(g.topDiv).insertBefore(g.hDiv).addClass("ui-state-default ui-jqgrid-toppager").width(g.width);u(a.p.toppager,"_t")}if(a.p.footerrow){g.sDiv=b("<div class='ui-jqgrid-sdiv'></div>")[0];H=b("<div class='ui-jqgrid-hbox"+(m=="rtl"?"-rtl":"")+"'></div>");b(g.sDiv).append(H).insertAfter(g.hDiv).width(g.width);b(H).append(ua);g.footers=b(".ui-jqgrid-ftable",
g.sDiv)[0].rows[0].cells;if(a.p.rownumbers)g.footers[0].className="ui-state-default jqgrid-rownum";R&&b(g.sDiv).hide()}if(a.p.caption){var Fa=a.p.datatype;if(a.p.hidegrid===true){b(".ui-jqgrid-titlebar-close",g.cDiv).click(function(c){var d=b.isFunction(a.p.onHeaderClick);if(a.p.gridstate=="visible"){b(".ui-jqgrid-bdiv, .ui-jqgrid-hdiv","#gview_"+a.p.id).slideUp("fast");a.p.pager&&b(a.p.pager).slideUp("fast");a.p.toppager&&b(a.p.toppager).slideUp("fast");if(a.p.toolbar[0]===true){a.p.toolbar[1]==
"both"&&b(g.ubDiv).slideUp("fast");b(g.uDiv).slideUp("fast")}a.p.footerrow&&b(".ui-jqgrid-sdiv","#gbox_"+a.p.id).slideUp("fast");b("span",this).removeClass("ui-icon-circle-triangle-n").addClass("ui-icon-circle-triangle-s");a.p.gridstate="hidden";if(d)R||a.p.onHeaderClick.call(a,a.p.gridstate,c)}else if(a.p.gridstate=="hidden"){b(".ui-jqgrid-hdiv, .ui-jqgrid-bdiv","#gview_"+a.p.id).slideDown("fast");a.p.pager&&b(a.p.pager).slideDown("fast");a.p.toppager&&b(a.p.toppager).slideDown("fast");if(a.p.toolbar[0]===
true){a.p.toolbar[1]=="both"&&b(g.ubDiv).slideDown("fast");b(g.uDiv).slideDown("fast")}a.p.footerrow&&b(".ui-jqgrid-sdiv","#gbox_"+a.p.id).slideDown("fast");b("span",this).removeClass("ui-icon-circle-triangle-s").addClass("ui-icon-circle-triangle-n");if(R){a.p.datatype=Fa;X();R=false}a.p.gridstate="visible";d&&a.p.onHeaderClick.call(a,a.p.gridstate,c)}return false});if(R){a.p.datatype="local";b(".ui-jqgrid-titlebar-close",g.cDiv).trigger("click")}}}else b(g.cDiv).hide();b(g.hDiv).after(g.bDiv).mousemove(function(c){if(g.resizing){g.dragMove(c);
return false}});b(".ui-jqgrid-labels",g.hDiv).bind("selectstart",function(){return false});b(document).mouseup(function(){if(g.resizing){g.dragEnd();return false}return true});this.updateColumns=function(){var c=this.rows[0],d=this;if(c){b("td",c).each(function(e){b(this).css("width",d.grid.headers[e].width+"px")});this.grid.cols=c.cells}return this};a.formatCol=F;a.sortData=xa;a.updatepager=la;a.formatter=function(c,d,e,l,n){return M(c,d,e,l,n)};b.extend(g,{populate:X,emptyRows:$});this.grid=g;a.addXmlData=
function(c){qa(c,a.grid.bDiv)};a.addJSONData=function(c){ra(c,a.grid.bDiv)};X();a.p.hiddengrid=false;b(window).unload(function(){b(this).empty();this.p=this.grid=null})}}})};b.jgrid.extend({getGridParam:function(f){var k=this[0];if(k.grid)return f?typeof k.p[f]!="undefined"?k.p[f]:null:k.p},setGridParam:function(f){return this.each(function(){this.grid&&typeof f==="object"&&b.extend(true,this.p,f)})},getDataIDs:function(){var f=[],k=0,i;this.each(function(){if((i=this.rows.length)&&i>0)for(;k<i;){f[k]=
this.rows[k].id;k++}});return f},setSelection:function(f,k){return this.each(function(){function i(a,q){var u=b(h.grid.bDiv)[0].clientHeight,y=b(h.grid.bDiv)[0].scrollTop,B=h.rows[a].offsetTop+h.rows[a].clientHeight;a=h.rows[a].offsetTop;if(q=="d")if(B>=u)b(h.grid.bDiv)[0].scrollTop=y+B-a;if(q=="u")if(a<y)b(h.grid.bDiv)[0].scrollTop=y-B+a}var h=this,g,j,m;if(f!==undefined){k=k===false?false:true;j=h.rows.namedItem(f+"");if(j!==null){if(h.p.selrow&&h.p.scrollrows===true){g=h.rows.namedItem(h.p.selrow).rowIndex;
m=h.rows.namedItem(f).rowIndex;if(m>=0)m>g?i(m,"d"):i(m,"u")}if(h.p.multiselect){h.p.selrow=j.id;m=b.inArray(h.p.selrow,h.p.selarrrow);if(m===-1){j.className!=="ui-subgrid"&&b(j).addClass("ui-state-highlight").attr("aria-selected","true");g=true;b("#jqg_"+b.jgrid.jqID(h.p.selrow),h.rows[j.rowIndex]).attr("checked",g);h.p.selarrrow.push(h.p.selrow);h.p.onSelectRow&&k&&h.p.onSelectRow.call(h,h.p.selrow,g)}else{j.className!=="ui-subgrid"&&b(j).removeClass("ui-state-highlight").attr("aria-selected","false");
g=false;b("#jqg_"+b.jgrid.jqID(h.p.selrow),h.rows[j.rowIndex]).attr("checked",g);h.p.selarrrow.splice(m,1);h.p.onSelectRow&&k&&h.p.onSelectRow.call(h,h.p.selrow,g);j=h.p.selarrrow[0];h.p.selrow=j===undefined?null:j}}else if(j.className!=="ui-subgrid"){h.p.selrow&&b("tr#"+b.jgrid.jqID(h.p.selrow),h.grid.bDiv).removeClass("ui-state-highlight").attr("aria-selected","false");h.p.selrow=j.id;b(j).addClass("ui-state-highlight").attr("aria-selected","true");h.p.onSelectRow&&k&&h.p.onSelectRow.call(h,h.p.selrow,
true)}}}})},resetSelection:function(){return this.each(function(){var f=this,k;if(f.p.multiselect){b(f.p.selarrrow).each(function(i,h){k=f.rows.namedItem(h);b(k).removeClass("ui-state-highlight").attr("aria-selected","false");b("#jqg_"+b.jgrid.jqID(h),k).attr("checked",false)});b("#cb_"+b.jgrid.jqID(f.p.id),f.grid.hDiv).attr("checked",false);f.p.selarrrow=[]}else if(f.p.selrow){b("tr#"+b.jgrid.jqID(f.p.selrow),f.grid.bDiv).removeClass("ui-state-highlight").attr("aria-selected","false");f.p.selrow=
null}f.p.savedRow=[]})},getRowData:function(f){var k={},i,h=false,g,j=0;this.each(function(){var m=this,a,q;if(typeof f=="undefined"){h=true;i=[];g=m.rows.length}else{q=m.rows.namedItem(f);if(!q)return k;g=1}for(;j<g;){if(h)q=m.rows[j];b("td",q).each(function(u){a=m.p.colModel[u].name;if(a!=="cb"&&a!=="subgrid")if(m.p.treeGrid===true&&a==m.p.ExpandColumn)k[a]=b.jgrid.htmlDecode(b("span:first",this).html());else try{k[a]=b.unformat(this,{rowId:q.id,colModel:m.p.colModel[u]},u)}catch(y){k[a]=b.jgrid.htmlDecode(b(this).html())}});
j++;if(h){i.push(k);k={}}}});return i?i:k},delRowData:function(f){var k=false,i,h,g;this.each(function(){var j=this;if(i=j.rows.namedItem(f)){g=i.rowIndex;b(i).remove();j.p.records--;j.p.reccount--;j.updatepager(true,false);k=true;if(j.p.multiselect){h=b.inArray(f,j.p.selarrrow);h!=-1&&j.p.selarrrow.splice(h,1)}if(f==j.p.selrow)j.p.selrow=null}else return false;g==0&&k&&j.updateColumns();if(j.p.altRows===true&&k){var m=j.p.altclass;b(j.rows).each(function(a){a%2==1?b(this).addClass(m):b(this).removeClass(m)})}});
return k},setRowData:function(f,k,i){var h,g=false;this.each(function(){var j=this,m,a,q=typeof i;if(!j.grid)return false;a=j.rows.namedItem(f);if(!a)return false;k&&b(this.p.colModel).each(function(u){h=this.name;if(k[h]!=undefined){m=j.formatter(f,k[h],u,k,"edit");j.p.treeGrid===true&&h==j.p.ExpandColumn?b("td:eq("+u+") > span:first",a).html(m).attr("title",b.jgrid.stripHtml(m)):b("td:eq("+u+")",a).html(m).attr("title",b.jgrid.stripHtml(m));g=true}});if(q==="string")b(a).addClass(i);else q==="object"&&
b(a).css(i)});return g},addRowData:function(f,k,i,h){i||(i="last");var g=false,j,m,a,q,u,y,B,K,J="",F,S,M;if(k){if(b.isArray(k)){F=true;i="last";S=f}else{k=[k];F=false}this.each(function(){var t=this,ia=k.length;u=t.p.rownumbers===true?1:0;a=t.p.multiselect===true?1:0;q=t.p.subGrid===true?1:0;if(!F)if(typeof f!="undefined")f+="";else{f=t.p.records+1+"";if(t.p.keyIndex!==false){cmn=t.p.colModel[t.p.keyIndex+a+q+u].name;if(typeof k[0][cmn]!="undefined")f=k[0][cmn]}}M=t.p.altclass;for(var aa=0,ja=b.isFunction(t.p.afterInsertRow)?
true:false;aa<ia;){data=k[aa];m="";if(F){try{f=data[S]}catch(pa){f=t.p.records+1}var $=t.p.altRows===true?(t.rows.length-1)%2==0?M:"":""}if(u){J=t.formatCol(u,1);m+='<td role="gridcell" class="ui-state-default jqgrid-rownum" '+J+">0</td>"}if(a){K='<input type="checkbox" id="jqg_'+f+'" class="cbox"/>';J=t.formatCol(u,1);m+='<td role="gridcell" '+J+">"+K+"</td>"}if(q)m+=b(t).jqGrid("addSubGridCell",a+u,1);for(B=a+q+u;B<this.p.colModel.length;B++){j=this.p.colModel[B].name;K=t.formatter(f,data[j],B,
data,"add");J=t.formatCol(B,1);m+='<td role="gridcell" '+J+' title="'+b.jgrid.stripHtml(K)+'">'+K+"</td>"}m='<tr id="'+f+'" role="row" class="ui-widget-content jqgrow ui-row-'+t.p.direction+" "+$+'">'+m+"</tr>";if(t.p.subGrid===true){m=b(m)[0];b(t).jqGrid("addSubGrid",m,a+u)}if(t.rows.length===0)b("table:first",t.grid.bDiv).append(m);else switch(i){case "last":b(t.rows[t.rows.length-1]).after(m);break;case "first":b(t.rows[0]).before(m);break;case "after":if(y=t.rows.namedItem(h))b(t.rows[y.rowIndex+
1]).hasClass("ui-subgrid")?b(t.rows[y.rowIndex+1]).after(m):b(y).after(m);break;case "before":if(y=t.rows.namedItem(h)){b(y).before(m);y=y.rowIndex}break}t.p.records++;t.p.reccount++;if(!t.grid.cols||!t.grid.cols.length)t.grid.cols=t.rows[0].cells;if(i==="first"||i==="before"&&y<=1||t.rows.length===1)t.updateColumns();ja&&t.p.afterInsertRow(t,f,data);aa++}if(t.p.altRows===true&&!F)if(i=="last")(t.rows.length-1)%2==1&&b(t.rows[t.rows.length-1]).addClass(M);else b(t.rows).each(function(T){T%2==1?b(this).addClass(M):
b(this).removeClass(M)});t.updatepager(true,true);g=true})}return g},footerData:function(f,k,i){function h(a){for(var q in a)return false;return true}var g,j=false,m={};if(typeof f=="undefined")f="get";if(typeof i!="boolean")i=true;f=f.toLowerCase();this.each(function(){var a=this,q;if(!a.grid||!a.p.footerrow)return false;if(f=="set")if(h(k))return false;j=true;b(this.p.colModel).each(function(u){g=this.name;if(f=="set"){if(k[g]!=undefined){q=i?a.formatter("",k[g],u,k,"edit"):k[g];b("tr.footrow td:eq("+
u+")",a.grid.sDiv).html(q).attr("title",b.jgrid.stripHtml(q));j=true}}else if(f=="get")m[g]=b("tr.footrow td:eq("+u+")",a.grid.sDiv).html()})});return f=="get"?m:j},ShowHideCol:function(f,k){return this.each(function(){var i=this,h=false;if(i.grid){if(typeof f==="string")f=[f];k=k!="none"?"":"none";var g=k==""?true:false;b(this.p.colModel).each(function(j){if(b.inArray(this.name,f)!==-1&&this.hidden===g){b("tr",i.grid.hDiv).each(function(){b("th:eq("+j+")",this).css("display",k)});b(i.rows).each(function(m){b("td:eq("+
j+")",i.rows[m]).css("display",k)});i.p.footerrow&&b("td:eq("+j+")",i.grid.sDiv).css("display",k);if(k=="none")i.p.tblwidth-=this.width;else i.p.tblwidth+=this.width;this.hidden=!g;h=true}});if(h===true){b("table:first",i.grid.hDiv).width(i.p.tblwidth);b("table:first",i.grid.bDiv).width(i.p.tblwidth);i.grid.hDiv.scrollLeft=i.grid.bDiv.scrollLeft;if(i.p.footerrow){b("table:first",i.grid.sDiv).width(i.p.tblwidth);i.grid.sDiv.scrollLeft=i.grid.bDiv.scrollLeft}}}})},hideCol:function(f){return this.each(function(){b(this).jqGrid("ShowHideCol",
f,"none")})},showCol:function(f){return this.each(function(){b(this).jqGrid("ShowHideCol",f,"")})},remapColumns:function(f,k,i){function h(m){var a;a=m.length?b.makeArray(m):b.extend({},m);b.each(f,function(q){m[q]=a[this]})}function g(m,a){b(">tr"+(a||""),m).each(function(){var q=this,u=b.makeArray(q.cells);b.each(f,function(){var y=u[this];y&&q.appendChild(y)})})}var j=this.get(0);h(j.p.colModel);h(j.p.colNames);h(j.grid.headers);g(b("thead:first",j.grid.hDiv),i&&":not(.ui-jqgrid-labels)");k&&g(b("tbody:first",
j.grid.bDiv),".jqgrow");j.p.footerrow&&g(b("tbody:first",j.grid.sDiv));if(j.p.remapColumns)if(j.p.remapColumns.length)h(j.p.remapColumns);else j.p.remapColumns=b.makeArray(f);j.p.lastsort=b.inArray(j.p.lastsort,f);if(j.p.treeGrid)j.p.expColInd=b.inArray(j.p.expColInd,f)},setGridWidth:function(f,k){return this.each(function(){var i=this,h,g=0,j=i.p.cellLayout,m,a=0,q=false,u=i.p.scrollOffset,y,B=0,K=0,J=0,F;if(i.grid){if(typeof k!="boolean")k=i.p.shrinkToFit;if(!isNaN(f)){f=parseInt(f,10);i.grid.width=
i.p.width=f;b("#gbox_"+i.p.id).css("width",f+"px");b("#gview_"+i.p.id).css("width",f+"px");b(i.grid.bDiv).css("width",f+"px");b(i.grid.hDiv).css("width",f+"px");i.p.pager&&b(i.p.pager).css("width",f+"px");if(i.p.toolbar[0]===true){b(i.grid.uDiv).css("width",f+"px");i.p.toolbar[1]=="both"&&b(i.grid.ubDiv).css("width",f+"px")}i.p.footerrow&&b(i.grid.sDiv).css("width",f+"px");if(k===false&&i.p.forceFit==true)i.p.forceFit=false;if(k===true){if(b.browser.safari)j=0;b.each(i.p.colModel,function(){if(this.hidden===
false){g+=parseInt(this.width,10);if(this.fixed){K+=this.width;B+=this.width+j}else a++;J++}});if(a!=0){i.p.tblwidth=g;y=f-j*a-B;if(!isNaN(i.p.height))if(b(i.grid.bDiv)[0].clientHeight<b(i.grid.bDiv)[0].scrollHeight){q=true;y-=u}g=0;var S=i.grid.cols.length>0;b.each(i.p.colModel,function(M){if(this.hidden===false&&!this.fixed){this.width=h=Math.floor(y/(i.p.tblwidth-K)*this.width);g+=h;i.grid.headers[M].width=h;i.grid.headers[M].el.style.width=h+"px";if(i.p.footerrow)i.grid.footers[M].style.width=
h+"px";if(S)i.grid.cols[M].style.width=h+"px";m=M}});F=0;if(q){if(f-B-(g+j*a)!==u)F=f-B-(g+j*a)-u}else if(Math.abs(f-B-(g+j*a))!==1)F=f-B-(g+j*a);i.p.colModel[m].width+=F;h=i.p.colModel[m].width;i.grid.headers[m].width=h;i.grid.headers[m].el.style.width=h+"px";if(S)i.grid.cols[m].style.width=h+"px";i.p.tblwidth=g+F+K+j*J;b("table:first",i.grid.bDiv).css("width",i.p.tblwidth+"px");b("table:first",i.grid.hDiv).css("width",i.p.tblwidth+"px");i.grid.hDiv.scrollLeft=i.grid.bDiv.scrollLeft;if(i.p.footerrow){i.grid.footers[m].style.width=
h+"px";b("table:first",i.grid.sDiv).css("width",i.p.tblwidth+"px")}}}}}})},setGridHeight:function(f){return this.each(function(){var k=this;if(k.grid){b(k.grid.bDiv).css({height:f+(isNaN(f)?"":"px")});k.p.height=f;k.p.scroll&&k.grid.populateVisible()}})},setCaption:function(f){return this.each(function(){this.p.caption=f;b("span.ui-jqgrid-title",this.grid.cDiv).html(f);b(this.grid.cDiv).show()})},setLabel:function(f,k,i,h){return this.each(function(){var g=this,j=-1;if(g.grid){if(isNaN(f))b(g.p.colModel).each(function(q){if(this.name==
f){j=q;return false}});else j=parseInt(f,10);if(j>=0){var m=b("tr.ui-jqgrid-labels th:eq("+j+")",g.grid.hDiv);if(k){var a=b(".s-ico",m);b("[id^=jqgh_]",m).empty().html(k).append(a);g.p.colNames[j]=k}if(i)typeof i==="string"?b(m).addClass(i):b(m).css(i);typeof h==="object"&&b(m).attr(h)}}})},setCell:function(f,k,i,h,g){return this.each(function(){var j=this,m=-1,a;if(j.grid){if(isNaN(k))b(j.p.colModel).each(function(u){if(this.name==k){m=u;return false}});else m=parseInt(k,10);if(m>=0)if(a=j.rows.namedItem(f)){var q=
b("td:eq("+m+")",a);if(i!==""){a=j.formatter(f,i,m,a,"edit");j.p.treeGrid&&b(".tree-wrap",b(q)).length>0?b("span",b(q)).html(a).attr("title",b.jgrid.stripHtml(a)):b(q).html(a).attr("title",b.jgrid.stripHtml(a))}if(typeof h==="string")h?b(q).addClass(h):b(q).removeClass();else h&&b(q).css(h);typeof g==="object"&&b(q).attr(g)}}})},getCell:function(f,k){var i=false;this.each(function(){var h=this,g=-1;if(h.grid){if(isNaN(k))b(h.p.colModel).each(function(a){if(this.name===k){g=a;return false}});else g=
parseInt(k,10);if(g>=0){var j=h.rows.namedItem(f);if(j)try{i=b.unformat(b("td:eq("+g+")",j),{rowId:j.id,colModel:h.p.colModel[g]},g)}catch(m){i=b.jgrid.htmlDecode(b("td:eq("+g+")",j).html())}}}});return i},getCol:function(f,k,i){var h=[],g,j=0;k=typeof k!="boolean"?false:k;if(typeof i=="undefined")i=false;this.each(function(){var m=this,a=-1;if(m.grid){if(isNaN(f))b(m.p.colModel).each(function(B){if(this.name===f){a=B;return false}});else a=parseInt(f,10);if(a>=0){var q=m.rows.length,u=0;if(q&&q>
0){for(;u<q;){try{g=b.unformat(b(m.rows[u].cells[a]),{rowId:m.rows[u].id,colModel:m.p.colModel[a]},a)}catch(y){g=b.jgrid.htmlDecode(m.rows[u].cells[a].innerHTML)}i?(j+=parseFloat(g)):k?h.push({id:m.rows[u].id,value:g}):(h[u]=g);u++}if(i)switch(i.toLowerCase()){case "sum":h=j;break;case "avg":h=j/q;break;case "count":h=q;break}}}}});return h},clearGridData:function(f){return this.each(function(){var k=this;if(k.grid){if(typeof f!="boolean")f=false;b("tbody:first tr",k.grid.bDiv).remove();k.p.footerrow&&
f&&b(".ui-jqgrid-ftable td",k.grid.sDiv).html("&#160;");k.p.selrow=null;k.p.selarrrow=[];k.p.savedRow=[];k.p.records=0;k.p.page="0";k.p.lastpage="0";k.p.reccount=0;k.updatepager(true,false)}})},getInd:function(f,k){var i=false,h;this.each(function(){if(h=this.rows.namedItem(f))i=k===true?h:h.rowIndex});return i}})})(jQuery);
(function(c){function u(a,b,d,e,h){var g=b;if(c.fn.fmatter[a])g=c.fn.fmatter[a](b,d,e,h);return g}c.fmatter={};c.fn.fmatter=function(a,b,d,e,h){d=c.extend({},c.jgrid.formatter,d);return u(a,b,d,e,h)};c.fmatter.util={NumberFormat:function(a,b){isNumber(a)||(a*=1);if(isNumber(a)){var d=a<0,e=a+"",h=b.decimalSeparator?b.decimalSeparator:".";if(isNumber(b.decimalPlaces)){var g=b.decimalPlaces;e=Math.pow(10,g);e=Math.round(a*e)/e+"";a=e.lastIndexOf(".");if(g>0){if(a<0){e+=h;a=e.length-1}else if(h!==".")e=
e.replace(".",h);for(;e.length-1-a<g;)e+="0"}}if(b.thousandsSeparator){g=b.thousandsSeparator;a=e.lastIndexOf(h);a=a>-1?a:e.length;h=e.substring(a);for(var f=-1,i=a;i>0;i--){f++;if(f%3===0&&i!==a&&(!d||i>1))h=g+h;h=e.charAt(i-1)+h}e=h}e=b.prefix?b.prefix+e:e;return e=b.suffix?e+b.suffix:e}else return a},DateFormat:function(a,b,d,e){var h=function(m,r){m=String(m);for(r=parseInt(r)||2;m.length<r;)m="0"+m;return m},g={m:1,d:1,y:1970,h:0,i:0,s:0},f=0,i,k,j=["i18n"];j.i18n={dayNames:e.dayNames,monthNames:e.monthNames};
if(a in e.masks)a=e.masks[a];b=b.split(/[\\\/:_;.\t\T\s-]/);a=a.split(/[\\\/:_;.\t\T\s-]/);i=0;for(k=a.length;i<k;i++){if(a[i]=="M"){f=c.inArray(b[i],j.i18n.monthNames);if(f!==-1&&f<12)b[i]=f+1}if(a[i]=="F"){f=c.inArray(b[i],j.i18n.monthNames);if(f!==-1&&f>11)b[i]=f+1-12}g[a[i].toLowerCase()]=parseInt(b[i],10)}g.m=parseInt(g.m)-1;f=g.y;if(f>=70&&f<=99)g.y=1900+g.y;else if(f>=0&&f<=69)g.y=2E3+g.y;f=new Date(g.y,g.m,g.d,g.h,g.i,g.s,0);if(d in e.masks)d=e.masks[d];else d||(d="Y-m-d");g=f.getHours();
a=f.getMinutes();b=f.getDate();i=f.getMonth()+1;k=f.getTimezoneOffset();var l=f.getSeconds(),o=f.getMilliseconds(),n=f.getDay(),p=f.getFullYear(),q=(n+6)%7+1,s=(new Date(p,i-1,b)-new Date(p,0,1))/864E5,t={d:h(b),D:j.i18n.dayNames[n],j:b,l:j.i18n.dayNames[n+7],N:q,S:e.S(b),w:n,z:s,W:q<5?Math.floor((s+q-1)/7)+1:Math.floor((s+q-1)/7)||(((new Date(p-1,0,1)).getDay()+6)%7<4?53:52),F:j.i18n.monthNames[i-1+12],m:h(i),M:j.i18n.monthNames[i-1],n:i,t:"?",L:"?",o:"?",Y:p,y:String(p).substring(2),a:g<12?e.AmPm[0]:
e.AmPm[1],A:g<12?e.AmPm[2]:e.AmPm[3],B:"?",g:g%12||12,G:g,h:h(g%12||12),H:h(g),i:h(a),s:h(l),u:o,e:"?",I:"?",O:(k>0?"-":"+")+h(Math.floor(Math.abs(k)/60)*100+Math.abs(k)%60,4),P:"?",T:(String(f).match(/\b(?:[PMCEA][SDP]T|(?:Pacific|Mountain|Central|Eastern|Atlantic) (?:Standard|Daylight|Prevailing) Time|(?:GMT|UTC)(?:[-+]\d{4})?)\b/g)||[""]).pop().replace(/[^-+\dA-Z]/g,""),Z:"?",c:"?",r:"?",U:Math.floor(f/1E3)};return d.replace(/\\.|[dDjlNSwzWFmMntLoYyaABgGhHisueIOPTZcrU]/g,function(m){return m in
t?t[m]:m.substring(1)})}};c.fn.fmatter.defaultFormat=function(a,b){return isValue(a)&&a!==""?a:b.defaultValue?b.defaultValue:"&#160;"};c.fn.fmatter.email=function(a,b){return isEmpty(a)?c.fn.fmatter.defaultFormat(a,b):'<a href="mailto:'+a+'">'+a+"</a>"};c.fn.fmatter.checkbox=function(a,b){var d=c.extend({},b.checkbox);isUndefined(b.colModel.formatoptions)||(d=c.extend({},d,b.colModel.formatoptions));b=d.disabled===true?"disabled":"";if(isEmpty(a)||isUndefined(a))a=c.fn.fmatter.defaultFormat(a,d);
a+="";a=a.toLowerCase();return'<input type="checkbox" '+(a.search(/(false|0|no|off)/i)<0?" checked='checked' ":"")+' value="'+a+'" offval="no" '+b+"/>"};c.fn.fmatter.link=function(a,b){var d={target:b.target},e="";isUndefined(b.colModel.formatoptions)||(d=c.extend({},d,b.colModel.formatoptions));if(d.target)e="target="+d.target;return isEmpty(a)?c.fn.fmatter.defaultFormat(a,b):"<a "+e+' href="'+a+'">'+a+"</a>"};c.fn.fmatter.showlink=function(a,b){var d={baseLinkUrl:b.baseLinkUrl,showAction:b.showAction,
addParam:b.addParam||"",target:b.target,idName:b.idName},e="";isUndefined(b.colModel.formatoptions)||(d=c.extend({},d,b.colModel.formatoptions));if(d.target)e="target="+d.target;idUrl=d.baseLinkUrl+d.showAction+"?"+d.idName+"="+b.rowId+d.addParam;return isString(a)?"<a "+e+' href="'+idUrl+'">'+a+"</a>":c.fn.fmatter.defaultFormat(a,b)};c.fn.fmatter.integer=function(a,b){var d=c.extend({},b.integer);isUndefined(b.colModel.formatoptions)||(d=c.extend({},d,b.colModel.formatoptions));if(isEmpty(a))return d.defaultValue;
return c.fmatter.util.NumberFormat(a,d)};c.fn.fmatter.number=function(a,b){var d=c.extend({},b.number);isUndefined(b.colModel.formatoptions)||(d=c.extend({},d,b.colModel.formatoptions));if(isEmpty(a))return d.defaultValue;return c.fmatter.util.NumberFormat(a,d)};c.fn.fmatter.currency=function(a,b){var d=c.extend({},b.currency);isUndefined(b.colModel.formatoptions)||(d=c.extend({},d,b.colModel.formatoptions));if(isEmpty(a))return d.defaultValue;return c.fmatter.util.NumberFormat(a,d)};c.fn.fmatter.date=
function(a,b,d,e){d=c.extend({},b.date);isUndefined(b.colModel.formatoptions)||(d=c.extend({},d,b.colModel.formatoptions));return!d.reformatAfterEdit&&e=="edit"?c.fn.fmatter.defaultFormat(a,b):isEmpty(a)?c.fn.fmatter.defaultFormat(a,b):c.fmatter.util.DateFormat(d.srcformat,a,d.newformat,d)};c.fn.fmatter.select=function(a,b){a+="";var d=false,e=[];if(!isUndefined(b.colModel.editoptions))d=b.colModel.editoptions.value;if(d){var h=b.colModel.editoptions.multiple===true?true:false,g=[],f;if(h){g=a.split(",");
g=c.map(g,function(l){return c.trim(l)})}if(isString(d))for(var i=d.split(";"),k=0,j=0;j<i.length;j++){f=i[j].split(":");if(f.length>2)f[1]=jQuery.map(f,function(l,o){if(o>0)return l}).join(":");if(h){if(jQuery.inArray(f[0],g)>-1){e[k]=f[1];k++}}else if(c.trim(f[0])==c.trim(a)){e[0]=f[1];break}}else if(isObject(d))if(h)e=jQuery.map(g,function(l){return d[l]});else e[0]=d[a]||""}a=e.join(", ");return a==""?c.fn.fmatter.defaultFormat(a,b):a};c.fn.fmatter.rowactions=function(a,b,d,e){switch(d){case "edit":d=
function(){c(".ui-inline-edit, .ui-inline-del","#"+a).show();c(".ui-inline-save, .ui-inline-cancel","#"+a).hide()};c("#"+b).jqGrid("editRow",a,e,null,null,null,{oper:"edit"},d,null,d);c(".ui-inline-edit, .ui-inline-del","#"+a).hide();c(".ui-inline-save, .ui-inline-cancel","#"+a).show();break;case "save":c("#"+b).jqGrid("saveRow",a,null,null,{oper:"edit"});c(".ui-inline-edit, .ui-inline-del","#"+a).show();c(".ui-inline-save, .ui-inline-cancel","#"+a).hide();break;case "cancel":c("#"+b).jqGrid("restoreRow",
a);c(".ui-inline-edit, .ui-inline-del","#"+a).show();c(".ui-inline-save, .ui-inline-cancel","#"+a).hide();break}};c.fn.fmatter.actions=function(a,b){var d={keys:false};isUndefined(b.colModel.formatoptions)||(d=c.extend(d,b.colModel.formatoptions));a=b.rowId;if(typeof a=="undefined"||isEmpty(a))return"";d="onclick=$.fn.fmatter.rowactions('"+a+"','"+b.gid+"','edit',"+d.keys+");";var e="<div style='margin-left:8px;'><div title='"+c.jgrid.nav.edittitle+"' style='float:left;cursor:pointer;' class='ui-pg-div ui-inline-edit' "+
d+"><span class='ui-icon ui-icon-pencil'></span></div>";d="onclick=jQuery('#"+b.gid+"').jqGrid('delGridRow','"+a+"');";e=e+"<div title='"+c.jgrid.nav.deltitle+"' style='float:left;margin-left:5px;' class='ui-pg-div ui-inline-del' "+d+"><span class='ui-icon ui-icon-trash'></span></div>";d="onclick=$.fn.fmatter.rowactions('"+a+"','"+b.gid+"','save',false);";e=e+"<div title='"+c.jgrid.edit.bSubmit+"' style='float:left;display:none' class='ui-pg-div ui-inline-save'><span class='ui-icon ui-icon-disk' "+
d+"></span></div>";d="onclick=$.fn.fmatter.rowactions('"+a+"','"+b.gid+"','cancel',false);";return e=e+"<div title='"+c.jgrid.edit.bCancel+"' style='float:left;display:none;margin-left:5px;' class='ui-pg-div ui-inline-cancel'><span class='ui-icon ui-icon-cancel' "+d+"></span></div></div>"};c.unformat=function(a,b,d,e){var h,g=b.colModel.formatter,f=b.colModel.formatoptions||{},i=/([\.\*\_\'\(\)\{\}\+\?\\])/g;unformatFunc=b.colModel.unformat||c.fn.fmatter[g]&&c.fn.fmatter[g].unformat;if(typeof unformatFunc!==
"undefined"&&isFunction(unformatFunc))h=unformatFunc(c(a).text(),b,a);else if(typeof g!=="undefined"&&isString(g)){h=c.jgrid.formatter||{};switch(g){case "integer":f=c.extend({},h.integer,f);b=f.thousandsSeparator.replace(i,"\\$1");b=new RegExp(b,"g");h=c(a).text().replace(b,"");break;case "number":f=c.extend({},h.number,f);b=f.thousandsSeparator.replace(i,"\\$1");b=new RegExp(b,"g");h=c(a).text().replace(b,"").replace(f.decimalSeparator,".");break;case "currency":f=c.extend({},h.currency,f);b=f.thousandsSeparator.replace(i,
"\\$1");b=new RegExp(b,"g");h=c(a).text().replace(b,"").replace(f.decimalSeparator,".").replace(f.prefix,"").replace(f.suffix,"");break;case "checkbox":f=b.colModel.editoptions?b.colModel.editoptions.value.split(":"):["Yes","No"];h=c("input",a).attr("checked")?f[0]:f[1];break;case "select":h=c.unformat.select(a,b,d,e);break;case "actions":return"";default:h=c(a).text()}}return h?h:e===true?c(a).text():c.jgrid.htmlDecode(c(a).html())};c.unformat.select=function(a,b,d,e){d=[];a=c(a).text();if(e==true)return a;
b=c.extend({},b.colModel.editoptions);if(b.value){var h=b.value;b=b.multiple===true?true:false;e=[];var g;if(b){e=a.split(",");e=c.map(e,function(j){return c.trim(j)})}if(isString(h))for(var f=h.split(";"),i=0,k=0;k<f.length;k++){g=f[k].split(":");if(b){if(jQuery.inArray(g[1],e)>-1){d[i]=g[0];i++}}else if(c.trim(g[1])==c.trim(a)){d[0]=g[0];break}}else if(isObject(h)){b||(e[0]=a);d=jQuery.map(e,function(j){var l;c.each(h,function(o,n){if(n==j){l=o;return false}});if(l)return l})}return d.join(", ")}else return a||
""};isValue=function(a){return isObject(a)||isString(a)||isNumber(a)||isBoolean(a)};isBoolean=function(a){return typeof a==="boolean"};isNull=function(a){return a===null};isNumber=function(a){return typeof a==="number"&&isFinite(a)};isString=function(a){return typeof a==="string"};isEmpty=function(a){if(!isString(a)&&isValue(a))return false;else if(!isValue(a))return true;a=c.trim(a).replace(/\&nbsp\;/ig,"").replace(/\&#160\;/ig,"");return a===""};isUndefined=function(a){return typeof a==="undefined"};
isObject=function(a){return a&&(typeof a==="object"||isFunction(a))||false};isFunction=function(a){return typeof a==="function"}})(jQuery);
(function(a){a.jgrid.extend({getColProp:function(e){var p={},b=this[0];if(b.grid){b=b.p.colModel;for(var k=0;k<b.length;k++)if(b[k].name==e){p=b[k];break}return p}},setColProp:function(e,p){return this.each(function(){if(this.grid)if(p)for(var b=this.p.colModel,k=0;k<b.length;k++)if(b[k].name==e){a.extend(this.p.colModel[k],p);break}})},sortGrid:function(e,p,b){return this.each(function(){var k=this,v=-1;if(k.grid){if(!e)e=k.p.sortname;for(var o=0;o<k.p.colModel.length;o++)if(k.p.colModel[o].index==
e||k.p.colModel[o].name==e){v=o;break}if(v!=-1){o=k.p.colModel[v].sortable;if(typeof o!=="boolean")o=true;if(typeof p!=="boolean")p=false;o&&k.sortData("jqgh_"+e,v,p,b)}}})},GridDestroy:function(){return this.each(function(){if(this.grid){this.p.pager&&a(this.p.pager).remove();var e=this.id;try{a("#gbox_"+e).remove()}catch(p){}}})},GridUnload:function(){return this.each(function(){if(this.grid){var e={id:a(this).attr("id"),cl:a(this).attr("class")};this.p.pager&&a(this.p.pager).empty().removeClass("ui-state-default ui-jqgrid-pager corner-bottom");
var p=document.createElement("table");a(p).attr({id:e.id});p.className=e.cl;e=this.id;a(p).removeClass("ui-jqgrid-btable");if(a(this.p.pager).parents("#gbox_"+e).length===1){a(p).insertBefore("#gbox_"+e).show();a(this.p.pager).insertBefore("#gbox_"+e)}else a(p).insertBefore("#gbox_"+e).show();a("#gbox_"+e).remove()}})},setGridState:function(e){return this.each(function(){if(this.grid){$t=this;if(e=="hidden"){a(".ui-jqgrid-bdiv, .ui-jqgrid-hdiv","#gview_"+$t.p.id).slideUp("fast");$t.p.pager&&a($t.p.pager).slideUp("fast");
if($t.p.toolbar[0]===true){$t.p.toolbar[1]=="both"&&a($t.grid.ubDiv).slideUp("fast");a($t.grid.uDiv).slideUp("fast")}$t.p.footerrow&&a(".ui-jqgrid-sdiv","#gbox_"+$s.p.id).slideUp("fast");a(".ui-jqgrid-titlebar-close span",$t.grid.cDiv).removeClass("ui-icon-circle-triangle-n").addClass("ui-icon-circle-triangle-s");$t.p.gridstate="hidden"}else if(e=="visible"){a(".ui-jqgrid-hdiv, .ui-jqgrid-bdiv","#gview_"+$t.p.id).slideDown("fast");$t.p.pager&&a($t.p.pager).slideDown("fast");if($t.p.toolbar[0]===true){$t.p.toolbar[1]==
"both"&&a($t.grid.ubDiv).slideDown("fast");a($t.grid.uDiv).slideDown("fast")}$t.p.footerrow&&a(".ui-jqgrid-sdiv","#gbox_"+$t.p.id).slideDown("fast");a(".ui-jqgrid-titlebar-close span",$t.grid.cDiv).removeClass("ui-icon-circle-triangle-s").addClass("ui-icon-circle-triangle-n");$t.p.gridstate="visible"}}})},updateGridRows:function(e,p,b){var k,v=false;this.each(function(){var o=this,l,j,s,g;if(!o.grid)return false;p||(p="id");e&&e.length>0&&a(e).each(function(){s=this;if(j=o.rows.namedItem(s[p])){g=
s[p];if(b===true)if(o.p.jsonReader.repeatitems===true){if(o.p.jsonReader.cell)s=s[o.p.jsonReader.cell];for(var d=0;d<s.length;d++){l=o.formatter(g,s[d],d,s,"edit");o.p.treeGrid===true&&k==o.p.ExpandColumn?a("td:eq("+d+") > span:first",j).html(l).attr("title",a.jgrid.stripHtml(l)):a("td:eq("+d+")",j).html(l).attr("title",a.jgrid.stripHtml(l))}return v=true}a(o.p.colModel).each(function(c){k=b===true?this.jsonmap||this.name:this.name;if(s[k]!=undefined){l=o.formatter(g,s[k],c,s,"edit");o.p.treeGrid===
true&&k==o.p.ExpandColumn?a("td:eq("+c+") > span:first",j).html(l).attr("title",a.jgrid.stripHtml(l)):a("td:eq("+c+")",j).html(l).attr("title",a.jgrid.stripHtml(l));v=true}})}})});return v},filterGrid:function(e,p){p=a.extend({gridModel:false,gridNames:false,gridToolbar:false,filterModel:[],formtype:"horizontal",autosearch:true,formclass:"filterform",tableclass:"filtertable",buttonclass:"filterbutton",searchButton:"Search",clearButton:"Clear",enableSearch:false,enableClear:false,beforeSearch:null,
afterSearch:null,beforeClear:null,afterClear:null,url:"",marksearched:true},p||{});return this.each(function(){var b=this;this.p=p;if(this.p.filterModel.length==0&&this.p.gridModel===false)alert("No filter is set");else if(e){this.p.gridid=e.indexOf("#")!=-1?e:"#"+e;var k=a(this.p.gridid).jqGrid("getGridParam","colModel");if(k){if(this.p.gridModel===true){var v=a(this.p.gridid)[0],o;a.each(k,function(d){var c=[];this.search=this.search===false?false:true;o=this.editrules&&this.editrules.searchhidden===
true?true:this.hidden===true?false:true;if(this.search===true&&o===true){c.label=b.p.gridNames===true?v.p.colNames[d]:"";c.name=this.name;c.index=this.index||this.name;c.stype=this.edittype||"text";if(c.stype!="select")c.stype="text";c.defval=this.defval||"";c.surl=this.surl||"";c.sopt=this.editoptions||{};c.width=this.width;b.p.filterModel.push(c)}})}else a.each(b.p.filterModel,function(){for(var d=0;d<k.length;d++)if(this.name==k[d].name){this.index=k[d].index||this.name;break}if(!this.index)this.index=
this.name});var l=function(){var d={},c=0,m,f=a(b.p.gridid)[0],h;f.p.searchdata={};a.isFunction(b.p.beforeSearch)&&b.p.beforeSearch();a.each(b.p.filterModel,function(){h=this.index;switch(this.stype){case "select":if(m=a("select[name="+h+"]",b).val()){d[h]=m;b.p.marksearched&&a("#jqgh_"+this.name,f.grid.hDiv).addClass("dirty-cell");c++}else{b.p.marksearched&&a("#jqgh_"+this.name,f.grid.hDiv).removeClass("dirty-cell");try{delete f.p.postData[this.index]}catch(q){}}break;default:if(m=a("input[name="+
h+"]",b).val()){d[h]=m;b.p.marksearched&&a("#jqgh_"+this.name,f.grid.hDiv).addClass("dirty-cell");c++}else{b.p.marksearched&&a("#jqgh_"+this.name,f.grid.hDiv).removeClass("dirty-cell");try{delete f.p.postData[this.index]}catch(t){}}}});var n=c>0?true:false;a.extend(f.p.postData,d);var i;if(b.p.url){i=a(f).jqGrid("getGridParam","url");a(f).jqGrid("setGridParam",{url:b.p.url})}a(f).jqGrid("setGridParam",{search:n}).trigger("reloadGrid",[{page:1}]);i&&a(f).jqGrid("setGridParam",{url:i});a.isFunction(b.p.afterSearch)&&
b.p.afterSearch()},j=function(){var d={},c,m=0,f=a(b.p.gridid)[0],h;a.isFunction(b.p.beforeClear)&&b.p.beforeClear();a.each(b.p.filterModel,function(){h=this.index;c=this.defval?this.defval:"";if(!this.stype)this.stype="text";switch(this.stype){case "select":var q;a("select[name="+h+"] option",b).each(function(u){if(u==0)this.selected=true;if(a(this).text()==c){this.selected=true;q=a(this).val();return false}});if(q){d[h]=q;b.p.marksearched&&a("#jqgh_"+this.name,f.grid.hDiv).addClass("dirty-cell");
m++}else{b.p.marksearched&&a("#jqgh_"+this.name,f.grid.hDiv).removeClass("dirty-cell");try{delete f.p.postData[this.index]}catch(t){}}break;case "text":a("input[name="+h+"]",b).val(c);if(c){d[h]=c;b.p.marksearched&&a("#jqgh_"+this.name,f.grid.hDiv).addClass("dirty-cell");m++}else{b.p.marksearched&&a("#jqgh_"+this.name,f.grid.hDiv).removeClass("dirty-cell");try{delete f.p.postData[this.index]}catch(r){}}break}});var n=m>0?true:false;a.extend(f.p.postData,d);var i;if(b.p.url){i=a(f).jqGrid("getGridParam",
"url");a(f).jqGrid("setGridParam",{url:b.p.url})}a(f).jqGrid("setGridParam",{search:n}).trigger("reloadGrid",[{page:1}]);i&&a(f).jqGrid("setGridParam",{url:i});a.isFunction(b.p.afterClear)&&b.p.afterClear()},s=a("<form name='SearchForm' style=display:inline;' class='"+this.p.formclass+"'></form>"),g=a("<table class='"+this.p.tableclass+"' cellspacing='0' cellpading='0' border='0'><tbody></tbody></table>");a(s).append(g);(function(){var d=document.createElement("tr"),c,m,f,h;b.p.formtype=="horizontal"&&
a(g).append(d);a.each(b.p.filterModel,function(n){f=document.createElement("td");a(f).append("<label for='"+this.name+"'>"+this.label+"</label>");h=document.createElement("td");var i=this;if(!this.stype)this.stype="text";switch(this.stype){case "select":if(this.surl)a(h).load(this.surl,function(){i.defval&&a("select",this).val(i.defval);a("select",this).attr({name:i.index||i.name,id:"sg_"+i.name});i.sopt&&a("select",this).attr(i.sopt);b.p.gridToolbar===true&&i.width&&a("select",this).width(i.width);
b.p.autosearch===true&&a("select",this).change(function(){l();return false})});else if(i.sopt.value){var q=i.sopt.value,t=document.createElement("select");a(t).attr({name:i.index||i.name,id:"sg_"+i.name}).attr(i.sopt);if(typeof q==="string"){n=q.split(";");for(var r,u=0;u<n.length;u++){q=n[u].split(":");r=document.createElement("option");r.value=q[0];r.innerHTML=q[1];if(q[1]==i.defval)r.selected="selected";t.appendChild(r)}}else if(typeof q==="object")for(u in q){n++;r=document.createElement("option");
r.value=u;r.innerHTML=q[u];if(q[u]==i.defval)r.selected="selected";t.appendChild(r)}b.p.gridToolbar===true&&i.width&&a(t).width(i.width);a(h).append(t);b.p.autosearch===true&&a(t).change(function(){l();return false})}break;case "text":t=this.defval?this.defval:"";a(h).append("<input type='text' name='"+(this.index||this.name)+"' id='sg_"+this.name+"' value='"+t+"'/>");i.sopt&&a("input",h).attr(i.sopt);if(b.p.gridToolbar===true&&i.width)a.browser.msie?a("input",h).width(i.width-4):a("input",h).width(i.width-
2);b.p.autosearch===true&&a("input",h).keypress(function(w){if((w.charCode?w.charCode:w.keyCode?w.keyCode:0)==13){l();return false}return this});break}if(b.p.formtype=="horizontal"){b.p.gridToolbar===true&&b.p.gridNames===false?a(d).append(h):a(d).append(f).append(h);a(d).append(h)}else{c=document.createElement("tr");a(c).append(f).append(h);a(g).append(c)}});h=document.createElement("td");if(b.p.enableSearch===true){m="<input type='button' id='sButton' class='"+b.p.buttonclass+"' value='"+b.p.searchButton+
"'/>";a(h).append(m);a("input#sButton",h).click(function(){l();return false})}if(b.p.enableClear===true){m="<input type='button' id='cButton' class='"+b.p.buttonclass+"' value='"+b.p.clearButton+"'/>";a(h).append(m);a("input#cButton",h).click(function(){j();return false})}if(b.p.enableClear===true||b.p.enableSearch===true)if(b.p.formtype=="horizontal")a(d).append(h);else{c=document.createElement("tr");a(c).append("<td>&#160;</td>").append(h);a(g).append(c)}})();a(this).append(s);this.triggerSearch=
l;this.clearSearch=j}else alert("Could not get grid colModel")}else alert("No target grid is set!")})},filterToolbar:function(e){e=a.extend({autosearch:true,searchOnEnter:true,beforeSearch:null,afterSearch:null,beforeClear:null,afterClear:null,searchurl:"",stringResult:false,groupOp:"AND"},e||{});return this.each(function(){function p(g,d){var c=a(g);c[0]!=null&&jQuery.each(d,function(){this.data!=null?c.bind(this.type,this.data,this.fn):c.bind(this.type,this.fn)})}var b=this,k=function(){var g={},
d=0,c,m,f={};a.each(b.p.colModel,function(){m=this.index||this.name;var r=this.searchoptions&&this.searchoptions.sopt?this.searchoptions.sopt[0]:"bw";switch(this.stype){case "select":if(c=a("select[name="+m+"]",b.grid.hDiv).val()){g[m]=c;f[m]=r;d++}else try{delete b.p.postData[m]}catch(u){}break;case "text":if(c=a("input[name="+m+"]",b.grid.hDiv).val()){g[m]=c;f[m]=r;d++}else try{delete b.p.postData[m]}catch(w){}break}});var h=d>0?true:false;if(e.stringResult){var n='{"groupOp":"'+e.groupOp+'","rules":[',
i=0;a.each(g,function(r,u){if(i>0)n+=",";n+='{"field":"'+r+'",';n+='"op":"'+f[r]+'",';n+='"data":"'+u+'"}';i++});n+="]}";a.extend(b.p.postData,{filters:n})}else a.extend(b.p.postData,g);var q;if(b.p.searchurl){q=b.p.url;a(b).jqGrid("setGridParam",{url:b.p.searchurl})}var t=false;if(a.isFunction(e.beforeSearch))t=e.beforeSearch.call(b);t||a(b).jqGrid("setGridParam",{search:h}).trigger("reloadGrid",[{page:1}]);q&&a(b).jqGrid("setGridParam",{url:q});a.isFunction(e.afterSearch)&&e.afterSearch()},v=a("<tr class='ui-search-toolbar' role='rowheader'></tr>"),
o,l,j,s;a.each(b.p.colModel,function(){var g=this;o=a("<th role='columnheader' class='ui-state-default ui-th-column ui-th-"+b.p.direction+"'></th>");l=a("<div style='width:100%;position:relative;height:100%;padding-right:0.3em;'></div>");this.hidden===true&&a(o).css("display","none");this.search=this.search===false?false:true;if(typeof this.stype=="undefined")this.stype="text";j=a.extend({},this.searchoptions||{});if(this.search)switch(this.stype){case "select":var d=this.surl||j.dataUrl;if(d)a.ajax(a.extend({url:d,
dataType:"html",complete:function(n){if(j.buildSelect!=null)(n=j.buildSelect(n))&&a(l).append(n);else a(l).append(n.responseText);j.defaultValue&&a("select",l).val(j.defaultValue);a("select",l).attr({name:g.index||g.name,id:"gs_"+g.name});j.attr&&a("select",l).attr(j.attr);a("select",l).css({width:"100%"});j.dataInit!=null&&j.dataInit(a("select",l)[0]);j.dataEvents!=null&&p(a("select",l)[0],j.dataEvents);e.autosearch===true&&a("select",l).change(function(){k();return false})}},a.jgrid.ajaxOptions,
b.p.ajaxSelectOptions||{}));else{var c;if(g.searchoptions&&g.searchoptions.value)c=g.searchoptions.value;else if(g.editoptions&&g.editoptions.value)c=g.editoptions.value;if(c){d=document.createElement("select");d.style.width="100%";a(d).attr({name:g.index||g.name,id:"gs_"+g.name});if(typeof c==="string"){c=c.split(";");for(var m,f,h=0;h<c.length;h++){m=c[h].split(":");f=document.createElement("option");f.value=m[0];f.innerHTML=m[1];d.appendChild(f)}}else if(typeof c==="object")for(m in c){f=document.createElement("option");
f.value=m;f.innerHTML=c[m];d.appendChild(f)}j.defaultValue&&a(d).val(j.defaultValue);j.attr&&a(d).attr(j.attr);j.dataInit!=null&&j.dataInit(d);j.dataEvents!=null&&p(d,j.dataEvents);a(l).append(d);e.autosearch===true&&a(d).change(function(){k();return false})}}break;case "text":d=j.defaultValue?j.defaultValue:"";a(l).append("<input type='text' style='width:95%;padding:0px;' name='"+(g.index||g.name)+"' id='gs_"+g.name+"' value='"+d+"'/>");j.attr&&a("input",l).attr(j.attr);j.dataInit!=null&&j.dataInit(a("input",
l)[0]);j.dataEvents!=null&&p(a("input",l)[0],j.dataEvents);if(e.autosearch===true)e.searchOnEnter?a("input",l).keypress(function(n){if((n.charCode?n.charCode:n.keyCode?n.keyCode:0)==13){k();return false}return this}):a("input",l).keydown(function(n){switch(n.which){case 9:case 16:case 37:case 38:case 39:case 40:case 27:break;default:s&&clearTimeout(s);s=setTimeout(function(){k()},500)}});break}a(o).append(l);a(v).append(o)});a("table thead",b.grid.hDiv).append(v);this.triggerToolbar=k;this.clearToolbar=
function(g){var d={},c,m=0,f;g=typeof g!="boolean"?true:g;a.each(b.p.colModel,function(){c=this.searchoptions&&this.searchoptions.defaultValue?this.searchoptions.defaultValue:"";f=this.index||this.name;switch(this.stype){case "select":var r;a("select[name="+f+"] option",b.grid.hDiv).each(function(x){if(x==0)this.selected=true;if(a(this).text()==c){this.selected=true;r=a(this).val();return false}});if(r){d[f]=r;m++}else try{delete b.p.postData[f]}catch(u){}break;case "text":a("input[name="+f+"]",b.grid.hDiv).val(c);
if(c){d[f]=c;m++}else try{delete b.p.postData[f]}catch(w){}break}});var h=m>0?true:false;if(e.stringResult){var n='{"groupOp":"'+e.groupOp+'","rules":[',i=0;a.each(d,function(r,u){if(i>0)n+=",";n+='{"field":"'+r+'",';n+='"op":"eq",';n+='"data":"'+u+'"}';i++});n+="]}";a.extend(b.p.postData,{filters:n})}else a.extend(b.p.postData,d);var q;if(b.p.searchurl){q=b.p.url;a(b).jqGrid("setGridParam",{url:b.p.searchurl})}var t=false;if(a.isFunction(e.beforeClear))t=e.beforeClear.call(b);t||g&&a(b).jqGrid("setGridParam",
{search:h}).trigger("reloadGrid",[{page:1}]);q&&a(b).jqGrid("setGridParam",{url:q});a.isFunction(e.afterClear)&&e.afterClear()};this.toggleToolbar=function(){var g=a("tr.ui-search-toolbar",b.grid.hDiv);g.css("display")=="none"?g.show():g.hide()}})}})})(jQuery);
(function(b){b.jgrid.extend({jqGridImport:function(a){a=b.extend({imptype:"xml",impstring:"",impurl:"",mtype:"GET",impData:{},xmlGrid:{config:"roots>grid",data:"roots>rows"},jsonGrid:{config:"grid",data:"data"},ajaxOptions:{}},a||{});return this.each(function(){var f=this,c=function(d,g){var e=b(g.xmlGrid.config,d)[0];g=b(g.xmlGrid.data,d)[0];if(xmlJsonClass.xml2json&&b.jgrid.parse){e=xmlJsonClass.xml2json(e," ");e=b.jgrid.parse(e);for(var i in e)var k=e[i];if(g){i=e.grid.datatype;e.grid.datatype=
"xmlstring";e.grid.datastr=d;b(f).jqGrid(k).jqGrid("setGridParam",{datatype:i})}else b(f).jqGrid(k)}else alert("xml2json or parse are not present")},j=function(d,g){if(d&&typeof d=="string"){var e=b.jgrid.parse(d);d=e[g.jsonGrid.config];if(g=e[g.jsonGrid.data]){e=d.datatype;d.datatype="jsonstring";d.datastr=g;b(f).jqGrid(d).jqGrid("setGridParam",{datatype:e})}else b(f).jqGrid(d)}};switch(a.imptype){case "xml":b.ajax(b.extend({url:a.impurl,type:a.mtype,data:a.impData,dataType:"xml",complete:function(d,
g){if(g=="success"){c(d.responseXML,a);b.isFunction(a.importComplete)&&a.importComplete(d)}}},a.ajaxOptions));break;case "xmlstring":if(a.impstring&&typeof a.impstring=="string"){var h=b.jgrid.stringToDoc(a.impstring);if(h){c(h,a);b.isFunction(a.importComplete)&&a.importComplete(h);a.impstring=null}h=null}break;case "json":b.ajax(b.extend({url:a.impurl,type:a.mtype,data:a.impData,dataType:"json",complete:function(d,g){if(g=="success"){j(d.responseText,a);b.isFunction(a.importComplete)&&a.importComplete(d)}}},
a.ajaxOptions));break;case "jsonstring":if(a.impstring&&typeof a.impstring=="string"){j(a.impstring,a);b.isFunction(a.importComplete)&&a.importComplete(a.impstring);a.impstring=null}break}})},jqGridExport:function(a){a=b.extend({exptype:"xmlstring",root:"grid",ident:"\t"},a||{});var f=null;this.each(function(){if(this.grid){var c=b.extend({},b(this).jqGrid("getGridParam"));if(c.rownumbers){c.colNames.splice(0,1);c.colModel.splice(0,1)}if(c.multiselect){c.colNames.splice(0,1);c.colModel.splice(0,1)}if(c.subgrid){c.colNames.splice(0,
1);c.colModel.splice(0,1)}if(c.treeGrid)for(var j in c.treeReader){c.colNames.splice(c.colNames.length-1);c.colModel.splice(c.colModel.length-1)}switch(a.exptype){case "xmlstring":f="<"+a.root+">"+xmlJsonClass.json2xml(c,a.ident)+"</"+a.root+">";break;case "jsonstring":f="{"+xmlJsonClass.toJson(c,a.root,a.ident)+"}";break}}});return f},excelExport:function(a){a=b.extend({exptype:"remote",url:null,oper:"oper",tag:"excel",exportOptions:{}},a||{});return this.each(function(){$t=this;if(this.grid)if(a.exptype==
"remote"){var f=b.extend({},this.p.postData);f[a.oper]=a.tag;f=jQuery.param(f);window.location=a.url+"?"+f}})}})})(jQuery);
var xmlJsonClass={xml2json:function(a,b){if(a.nodeType===9)a=a.documentElement;a=this.toJson(this.toObj(this.removeWhite(a)),a.nodeName,"\t");return"{\n"+b+(b?a.replace(/\t/g,b):a.replace(/\t|\n/g,""))+"\n}"},json2xml:function(a,b){var g=function(d,c,j){var i="",k,h;if(d instanceof Array)if(d.length===0)i+=j+"<"+c+">__EMPTY_ARRAY_</"+c+">\n";else{k=0;for(h=d.length;k<h;k+=1){var l=j+g(d[k],c,j+"\t")+"\n";i+=l}}else if(typeof d==="object"){k=false;i+=j+"<"+c;for(h in d)if(d.hasOwnProperty(h))if(h.charAt(0)===
"@")i+=" "+h.substr(1)+'="'+d[h].toString()+'"';else k=true;i+=k?">":"/>";if(k){for(h in d)if(d.hasOwnProperty(h))if(h==="#text")i+=d[h];else if(h==="#cdata")i+="<![CDATA["+d[h]+"]]\>";else if(h.charAt(0)!=="@")i+=g(d[h],h,j+"\t");i+=(i.charAt(i.length-1)==="\n"?j:"")+"</"+c+">"}}else i+=typeof d==="function"?j+"<"+c+"><![CDATA["+d+"]]\></"+c+">":d.toString()==='""'||d.toString().length===0?j+"<"+c+">__EMPTY_STRING_</"+c+">":j+"<"+c+">"+d.toString()+"</"+c+">";return i},e="",f;for(f in a)if(a.hasOwnProperty(f))e+=
g(a[f],f,"");return b?e.replace(/\t/g,b):e.replace(/\t|\n/g,"")},toObj:function(a){var b={},g=/function/i;if(a.nodeType===1){if(a.attributes.length){var e;for(e=0;e<a.attributes.length;e+=1)b["@"+a.attributes[e].nodeName]=(a.attributes[e].nodeValue||"").toString()}if(a.firstChild){var f=e=0,d=false,c;for(c=a.firstChild;c;c=c.nextSibling)if(c.nodeType===1)d=true;else if(c.nodeType===3&&c.nodeValue.match(/[^ \f\n\r\t\v]/))e+=1;else if(c.nodeType===4)f+=1;if(d)if(e<2&&f<2){this.removeWhite(a);for(c=
a.firstChild;c;c=c.nextSibling)if(c.nodeType===3)b["#text"]=this.escape(c.nodeValue);else if(c.nodeType===4)if(g.test(c.nodeValue))b[c.nodeName]=[b[c.nodeName],c.nodeValue];else b["#cdata"]=this.escape(c.nodeValue);else if(b[c.nodeName])if(b[c.nodeName]instanceof Array)b[c.nodeName][b[c.nodeName].length]=this.toObj(c);else b[c.nodeName]=[b[c.nodeName],this.toObj(c)];else b[c.nodeName]=this.toObj(c)}else if(a.attributes.length)b["#text"]=this.escape(this.innerXml(a));else b=this.escape(this.innerXml(a));
else if(e)if(a.attributes.length)b["#text"]=this.escape(this.innerXml(a));else{b=this.escape(this.innerXml(a));if(b==="__EMPTY_ARRAY_")b="[]";else if(b==="__EMPTY_STRING_")b=""}else if(f)if(f>1)b=this.escape(this.innerXml(a));else for(c=a.firstChild;c;c=c.nextSibling)if(g.test(a.firstChild.nodeValue)){b=a.firstChild.nodeValue;break}else b["#cdata"]=this.escape(c.nodeValue)}if(!a.attributes.length&&!a.firstChild)b=null}else if(a.nodeType===9)b=this.toObj(a.documentElement);else alert("unhandled node type: "+
a.nodeType);return b},toJson:function(a,b,g){var e=b?'"'+b+'"':"";if(a==="[]")e+=b?":[]":"[]";else if(a instanceof Array){var f,d,c=[];d=0;for(f=a.length;d<f;d+=1)c[d]=this.toJson(a[d],"",g+"\t");e+=(b?":[":"[")+(c.length>1?"\n"+g+"\t"+c.join(",\n"+g+"\t")+"\n"+g:c.join(""))+"]"}else if(a===null)e+=(b&&":")+"null";else if(typeof a==="object"){f=[];for(d in a)if(a.hasOwnProperty(d))f[f.length]=this.toJson(a[d],d,g+"\t");e+=(b?":{":"{")+(f.length>1?"\n"+g+"\t"+f.join(",\n"+g+"\t")+"\n"+g:f.join(""))+
"}"}else if(typeof a==="string"){g=/function/i;f=a.toString();e+=/(^-?\d+\.?\d*$)/.test(f)||g.test(f)||f==="false"||f==="true"?(b&&":")+f:(b&&":")+'"'+a+'"'}else e+=(b&&":")+a.toString();return e},innerXml:function(a){var b="";if("innerHTML"in a)b=a.innerHTML;else{var g=function(e){var f="",d;if(e.nodeType===1){f+="<"+e.nodeName;for(d=0;d<e.attributes.length;d+=1)f+=" "+e.attributes[d].nodeName+'="'+(e.attributes[d].nodeValue||"").toString()+'"';if(e.firstChild){f+=">";for(d=e.firstChild;d;d=d.nextSibling)f+=
g(d);f+="</"+e.nodeName+">"}else f+="/>"}else if(e.nodeType===3)f+=e.nodeValue;else if(e.nodeType===4)f+="<![CDATA["+e.nodeValue+"]]\>";return f};for(a=a.firstChild;a;a=a.nextSibling)b+=g(a)}return b},escape:function(a){return a.replace(/[\\]/g,"\\\\").replace(/[\"]/g,'\\"').replace(/[\n]/g,"\\n").replace(/[\r]/g,"\\r")},removeWhite:function(a){a.normalize();var b;for(b=a.firstChild;b;)if(b.nodeType===3)if(b.nodeValue.match(/[^ \f\n\r\t\v]/))b=b.nextSibling;else{var g=b.nextSibling;a.removeChild(b);
b=g}else{b.nodeType===1&&this.removeWhite(b);b=b.nextSibling}return a}};
